-- No-op as of the custom hash-based migrator (apps/server/src/db/migrator.ts).
--
-- This migration originally backfilled the three ALTER statements from
-- 0100_remote_users.sql that were silently dropped by drizzle's bun-sqlite
-- migrator: that migrator runs each chunk via db.run(), which under Bun's
-- SQLite driver only executes the first statement of a multi-statement
-- string. 0100 packs four statements into its second chunk, so the three
-- ALTERs after the CREATE UNIQUE INDEX never landed.
--
-- The replacement migrator runs each chunk via sqlite.exec(), which
-- executes every statement in the buffer, so 0100 now applies in full on
-- fresh installs and this backfill is redundant. The file is retained as a
-- no-op so the journal entry remains valid and existing installs that
-- already have this migration recorded in __drizzle_migrations continue to
-- match by hash on subsequent boots.
