<script lang="ts">
import { onDestroy, onMount, untrack } from "svelte";

const TOOL_CALL_ROW_H = 14; // px — 10px font × 1.4 line-height

import type { WalkthroughBlock, WalkthroughMode, WalkthroughSemanticStep } from "@revv/shared";
import RefreshCw from "phosphor-svelte/lib/ArrowsClockwise";
import AlertTriangle from "phosphor-svelte/lib/Warning";
import { toast } from "svelte-sonner";
import { mermaidDiagrams } from "$lib/actions/mermaid.svelte";
import { API_BASE_URL } from "$lib/api/base-url";
import { Shimmer } from "$lib/components/ai/shimmer";
import { ThoughtsReveal } from "$lib/components/ai/thoughts";
import { ToolActivityGroup } from "$lib/components/ai/tool";
import { Button } from "$lib/components/ui/button";
import { Dotmatrix } from "$lib/components/ui/dotmatrix/index.js";
import FileBadge from "$lib/components/ui/FileBadge.svelte";
import { Progress } from "$lib/components/ui/progress";
import { Separator } from "$lib/components/ui/separator";
import { gsapFadeY, tokens } from "$lib/motion";
import { getRepositories } from "$lib/stores/prs.svelte";
import {
  clearPendingWalkthroughBlockJump,
  getPendingWalkthroughBlockJump,
  getReviewMode,
  jumpToDiffLine,
} from "$lib/stores/review.svelte";
import { getResolvedTheme } from "$lib/stores/theme.svelte";
import {
  getBlocks,
  getCloneInProgress,
  getCloneRepoId,
  getExplorationSteps,
  getGeneratedBy,
  getIsLiveGeneration,
  getIsStreaming,
  getIsSuperseded,
  getIssues,
  getLastCompletedPhase,
  getLastWalkthroughEventAt,
  getPhase,
  getProviderConfig,
  getRatings,
  getRiskLevel,
  getSemanticSteps,
  getSentiment,
  getSource,
  getStreamError,
  getStreamStartedAt,
  getSummary,
  getTimeline,
  hasBlockAnimated,
  hasContainerAnimated,
  hasIssueAnimated,
  hydrateFromCache,
  markBlockAnimated,
  markContainerAnimated,
  markIssueAnimated,
  pollCloneUntilResolved,
  prepareEntry,
  regenerate,
  startWalkthrough,
  stopClonePoll,
} from "$lib/stores/walkthrough.svelte";
import { type GroupableActivity, isExplorationActivity } from "$lib/utils/activity-groups";
import { initHighlighter } from "$lib/utils/code-highlight.svelte";
import { renderMarkdown } from "$lib/utils/markdown";
import { authHeaders } from "$lib/utils/session-token";
import { groupIssuesBySeverityWithIndex } from "$lib/utils/walkthrough-issues";
import IssueCard from "./IssueCard.svelte";
import WalkthroughRatingsGrid from "./WalkthroughRatingsGrid.svelte";
import WalkthroughSection from "./WalkthroughSection.svelte";

interface Props {
  prId: string;
  scrollRoot?: HTMLElement | undefined;
  isActive?: boolean;
}

let { prId, scrollRoot, isActive = true }: Props = $props();

const blocks = $derived(getBlocks());
const semanticSteps = $derived(getSemanticSteps());
const summary = $derived(getSummary());
const riskLevel = $derived(getRiskLevel());
const isStreaming = $derived(getIsStreaming());
const streamError = $derived(getStreamError());
const explorationSteps = $derived(getExplorationSteps());
const timeline = $derived(getTimeline());
const phase = $derived(getPhase());
const streamStartedAt = $derived(getStreamStartedAt());
const issues = $derived(getIssues());
const issueGroups = $derived(groupIssuesBySeverityWithIndex(issues));
const ratings = $derived(getRatings());
const isLiveGeneration = $derived(getIsLiveGeneration());
const cloneInProgress = $derived(getCloneInProgress());
const cloneRepoId = $derived(getCloneRepoId());
const repositories = $derived(getRepositories());
const selectedMode = $derived(getReviewMode(prId));
const cloneRepo = $derived(cloneRepoId ? repositories.find((r) => r.id === cloneRepoId) : null);
const cloneError = $derived(cloneRepo?.cloneError ?? null);
// Phase C markdown — rendered inline as its own sentiment card when set.
// Replaces the legacy heuristic of sniffing markdown blocks for a `##
// Overall Sentiment` heading.
const sentiment = $derived(getSentiment());
const renderedSentiment = $derived(sentiment ? renderMarkdown(sentiment) : "");
// Pointer into the A→B→C→D pipeline — drives the 4-dot header indicator.
const lastCompletedPhase = $derived(getLastCompletedPhase());
// Newer commit invalidated this walkthrough mid-render.
const superseded = $derived(getIsSuperseded());
// Attribution + cache-source — drives the mono footer (matches the recap
// detail footer pattern) shown under the walkthrough body. Leads with the
// originating user when available, falls back to the model name, then trails
// off with the provider/thinking effort and cache origin.
const generatedBy = $derived(getGeneratedBy());
const providerConfig = $derived(getProviderConfig());
const walkthroughSource = $derived(getSource());

const footerParts: string[] = $derived.by(() => {
  const parts: string[] = [];
  if (generatedBy?.githubLogin) {
    parts.push(`Generated by @${generatedBy.githubLogin}`);
    if (providerConfig?.model) parts.push(providerConfig.model);
  } else if (providerConfig?.model) {
    parts.push(`Generated by ${providerConfig.model}`);
  }
  if (providerConfig?.thinkingEffort) {
    parts.push(`thinking: ${providerConfig.thinkingEffort}`);
  }
  if (walkthroughSource === "remote") {
    parts.push("loaded from team cache");
  }
  return parts;
});

// ── Elapsed time ────────────────────────────────────────────────────
let elapsedSeconds = $state(0);
let elapsedTimer: ReturnType<typeof setInterval> | null = null;
let walkthroughDebounce: ReturnType<typeof setTimeout> | undefined;
let hydrating = $state(true);
let hydratedForMode: WalkthroughMode | null = $state(null);
let lastStreamErrorToast: string | null = null;
let lastCloneErrorToast: string | null = null;
let lastSupersededToastPrId: string | null = null;

$effect(() => {
  if (!isActive || !streamError) {
    if (!streamError) lastStreamErrorToast = null;
    return;
  }

  const key = `${prId}:${streamError}`;
  if (lastStreamErrorToast === key) return;
  lastStreamErrorToast = key;

  toast.error("Walkthrough failed", {
    id: `walkthrough-error-${prId}`,
    description: streamError,
    duration: 8000,
  });
});

$effect(() => {
  if (!isActive || !cloneError) {
    if (!cloneError) lastCloneErrorToast = null;
    return;
  }

  const key = `${cloneRepoId ?? "unknown"}:${cloneError}`;
  if (lastCloneErrorToast === key) return;
  lastCloneErrorToast = key;

  toast.error("Repository clone failed", {
    id: `repo-clone-error-${cloneRepoId ?? prId}`,
    description: cloneError,
    duration: 8000,
  });
});

$effect(() => {
  if (!isActive || !superseded) {
    if (!superseded) lastSupersededToastPrId = null;
    return;
  }

  if (lastSupersededToastPrId === prId) return;
  lastSupersededToastPrId = prId;

  toast.warning("This walkthrough is outdated", {
    id: `walkthrough-superseded-${prId}`,
    description: "The PR has new commits since this review was generated.",
    action: {
      label: "Regenerate",
      onClick: () => handleRegenerate(),
    },
    duration: Number.POSITIVE_INFINITY,
  });
});

$effect(() => {
  if (isStreaming && streamStartedAt) {
    elapsedSeconds = Math.floor((Date.now() - streamStartedAt) / 1000);
    elapsedTimer = setInterval(() => {
      if (streamStartedAt) {
        elapsedSeconds = Math.floor((Date.now() - streamStartedAt) / 1000);
      }
    }, 1000);
  } else {
    if (elapsedTimer) {
      clearInterval(elapsedTimer);
      elapsedTimer = null;
    }
  }
  return () => {
    if (elapsedTimer) {
      clearInterval(elapsedTimer);
      elapsedTimer = null;
    }
  };
});

// ── Stream-stall watchdog ───────────────────────────────────────────
// SSE delivery is best-effort (doctrine invariant #8): a fast-failing job
// (e.g. an agent usage-limit hit that errors in <1s) can have its terminal
// `lifecycle:error` envelope — along with `lifecycle:started`/`phase` — miss
// this client entirely (broadcast/registration race, transient gap). The
// connection-level dead-socket watchdog in events.svelte.ts never fires
// because heartbeats keep flowing, so the entry stays `isStreaming` forever
// and the error never surfaces. Mirrors the clone poller below: when a live
// stream goes silent past the threshold, re-hydrate from `/current`, which is
// authoritative for the terminal status regardless of SSE delivery.
//
// Two thresholds: a tight one before the first substantive SSE event confirms
// the job is live (`lifecycle:started` should land within ~1-2s of Generate),
// and a heartbeat-tolerant one afterward (the server emits a `phase` heartbeat
// every 45s, so a genuinely-alive job is never silent that long).
const STREAM_START_STALL_MS = 20_000;
const STREAM_STALL_MS = 90_000;
const STALL_CHECK_INTERVAL_MS = 5_000;
let stallTimer: ReturnType<typeof setInterval> | null = null;
let lastStallReconcileAt = 0;
$effect(() => {
  if (!isStreaming || cloneInProgress) {
    if (stallTimer) {
      clearInterval(stallTimer);
      stallTimer = null;
    }
    return;
  }
  const watchedPrId = prId;
  stallTimer = setInterval(() => {
    const threshold = isLiveGeneration ? STREAM_STALL_MS : STREAM_START_STALL_MS;
    const lastActivity = Math.max(
      getLastWalkthroughEventAt(watchedPrId) ?? 0,
      streamStartedAt ?? 0,
    );
    const now = Date.now();
    if (now - lastActivity <= threshold) return;
    // Gate so we reconcile at most once per window — for a genuinely-still-
    // generating row `/current` keeps `isStreaming` true and doesn't refresh
    // the activity clock, which would otherwise hammer the endpoint every tick.
    if (now - lastStallReconcileAt <= threshold) return;
    lastStallReconcileAt = now;
    void hydrateFromCache(watchedPrId, { activate: false, mode: selectedMode });
  }, STALL_CHECK_INTERVAL_MS);
  return () => {
    if (stallTimer) {
      clearInterval(stallTimer);
      stallTimer = null;
    }
  };
});

function formatElapsed(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  if (m === 0) return `${s}s`;
  return `${m}m ${s.toString().padStart(2, "0")}s`;
}

// analyzing happens in the same agent turn as the last exploration step;
// map it to exploring so the skeleton phase check works correctly.
function normalizePhase(p: string): string {
  if (p === "connecting" || p === "analyzing") return "exploring";
  if (p === "finishing") return "writing";
  return p;
}

// ── Chapters stepper (Overview → Diff → Sentiment → Rating) ─────────
// Active chapter is the one the agent is *currently writing*, not the
// one that just finished. The pipeline pointer transitions like this:
//
//   set_overview        → 'A'  (Phase A done; Phase B starts on next call)
//   first add_diff_step → 'B'  (Phase B *started* — more diff steps coming)
//   set_sentiment       → 'C'  (Phase B closed, Phase C done; Phase D next)
//   9th rate_axis       → 'D'  (everything done)
//
// So `'B'` does NOT mean "diff is complete" — it means "diff in progress
// with at least one step persisted". Mapping `'B'` to chapter 2 (Sentiment)
// is the off-by-one bug: diff blocks are still streaming. We map both
// `'A'` and `'B'` to chapter 1 (Diff). Sentiment shows briefly between
// sentiment landing (`'C'`, ratings still empty) and the first rating
// arriving — a narrow window, but the only honest place to highlight it.
const PHASE_TO_INDEX: Record<"none" | "A" | "B" | "C" | "D", number> = {
  none: 0,
  A: 1,
  B: 1,
  C: 3,
  D: 3,
};
const activeChapterIndex = $derived.by(() => {
  // Prefer the strongest content signal we have: a rating landing means
  // we're in Phase D, sentiment landing means we're in Phase C. Falling
  // back to `lastCompletedPhase` only when no later content is visible
  // means a missed `phase:advanced` envelope can't strand the stepper on
  // Diff Analysis while Sentiment / Rating cards render below.
  if (ratings.length > 0) return 3;
  if (sentiment !== null) return 2;
  return PHASE_TO_INDEX[lastCompletedPhase];
});

const CHAPTERS = [
  {
    id: "overview",
    label: "Overview",
    blurb: "What changed and why",
    activeBlurb: "Reading the diff…",
    spinner: "ripple",
    targetId: "walkthrough-overview",
  },
  {
    id: "diff",
    label: "Diff Analysis",
    blurb: "Hunk-by-hunk reasoning",
    activeBlurb: "Analyzing hunks…",
    spinner: "diagonal",
    targetId: "walkthrough-diff",
  },
  {
    id: "sentiment",
    label: "Sentiment",
    blurb: "Overall read on the PR",
    activeBlurb: "Forming a verdict…",
    spinner: "collapse",
    targetId: "walkthrough-sentiment",
  },
  {
    id: "rated",
    label: "Rating",
    blurb: "Across 9 axis",
    activeBlurb: "Scoring each axis…",
    spinner: "prism-bloom",
    targetId: "walkthrough-rating",
  },
] as const;

// ── Recent tool calls under the active chapter ───────────────────────
// The active chapter cell renders a vertical list of the last 3 tool
// calls scoped to the *current* chapter. When the chapter advances we
// reset the floor to the count at that moment, so explorations from
// earlier chapters don't bleed forward into the new chapter's window.
//
// `chapterStartIndex` re-evaluates only when `activeChapterIndex`
// changes. Inside the body we read `explorationSteps.length` via
// `untrack` so the derived isn't subscribed to it (which would defeat
// the floor by re-snapping every time a new step arrives).
const TOOL_CALL_WINDOW = 3;
const chapterStartIndex = $derived.by(() => {
  // Reading `activeChapterIndex` makes this derived re-run on chapter
  // transitions; the void avoids the unused-expression warning while
  // still establishing the dependency.
  void activeChapterIndex;
  return untrack(() => explorationSteps.length);
});
// Pair each step with its absolute index so the keyed `{#each}` can
// use a collision-proof identity. Two consecutive `add_diff_step` calls
// share the same toolName + summary and crashed Svelte with
// `each_key_duplicate`, which freezes the whole component — that's the
// crash that made later chapters / ratings appear missing.
const recentExplorationSteps = $derived.by(() => {
  const start = Math.max(chapterStartIndex, explorationSteps.length - TOOL_CALL_WINDOW);
  return explorationSteps.slice(start).map((step, i) => ({ step, ordinal: start + i }));
});

// "All phases done" needs actual evidence of completion. A fresh PR with
// no content shouldn't flash all checkmarks just because !isStreaming — so
// we require that we actually have SOMETHING to show for it.
const hasWalkthroughContent = $derived(summary !== null || blocks.length > 0 || ratings.length > 0);

// ── Stepper visibility ──────────────────────────────────────────────
// Visible once hydration is done AND there is content to navigate (summary,
// blocks, or an active stream). Hidden during hydration (no flash before the
// cache is read) and when the walkthrough is empty (no content at all).
const stepperVisible = $derived(
  !hydrating && (summary !== null || blocks.length > 0 || isStreaming),
);

// ── Stagger tracking ────────────────────────────────────────────────
// Assign a per-block entrance delay the first time each block is
// observed. Blocks added in the same reactive tick form an "arrival
// batch" and cascade — so a cached walkthrough, a mid-stream tick,
// or an end-of-stream flush all fan out smoothly instead of slamming
// in as a wall of text. Delays are memoized so later re-renders
// don't re-trigger animations for blocks already on screen.

const STAGGER_MS = 85;
const STAGGER_CAP = 10;

// Legacy-row suppression: older walkthroughs (pre-Phase C field) encoded
// the sentiment paragraph as a markdown block starting with "## Overall
// Sentiment". When the new `sentiment` field is populated, we drop any
// such block here so rehydrated data doesn't render the paragraph twice.
// When `sentiment` is null we leave legacy blocks in place — they're the
// only copy we have.
const visibleBlocks = $derived.by(() => {
  if (sentiment === null) return blocks;
  return blocks.filter(
    (b) => !(b.type === "markdown" && b.content.trimStart().startsWith("## Overall Sentiment")),
  );
});

// ── Per-chapter availability ────────────────────────────────────────
// A chapter is "available" when its target section has been written —
// clicking it should land on real content, not an empty anchor. Used
// post-streaming to gate clickability and pick the right visual state.
const chapterAvailability = $derived([
  summary !== null,
  visibleBlocks.length > 0,
  sentiment !== null,
  ratings.length > 0,
]);

// Show a skeleton placeholder at the bottom of the diff section while
// Phase B is active — i.e. overview landed but diff analysis hasn't
// finished (more steps may still arrive). Defensively gate on
// `sentiment === null` and `ratings.length === 0` too: if any Phase C/D
// content has landed the agent has moved past Phase B, even if the
// `phase:advanced` envelope hasn't reached us yet (replay races, dropped
// frames, etc.). Without that guard the shimmer stays visible underneath
// the Overall Sentiment card.
const showDiffSkeleton = $derived(
  isStreaming &&
    sentiment === null &&
    ratings.length === 0 &&
    (lastCompletedPhase === "none" || lastCompletedPhase === "A" || lastCompletedPhase === "B"),
);

// Interleaved view: walks the chronological `timeline` (mixed thoughts
// + exploration tool calls) and emits a render list where consecutive
// exploration calls between thoughts collapse into a single group (so
// the "Exploring · N reads, M searches" shimmer/odometer still works
// inside each chronological segment). MCP write tools are filtered
// out for the same reason as above. Thoughts are emitted as discrete
// markdown blocks; each entry keeps its `timeline` id so streaming
// re-renders are stable.
type InterleavedRenderEntry =
  | { readonly kind: "thought"; readonly id: string; readonly text: string }
  | {
      readonly kind: "explorations";
      readonly id: string;
      readonly items: readonly GroupableActivity[];
    };
const interleavedEntries = $derived.by<readonly InterleavedRenderEntry[]>(() => {
  const out: InterleavedRenderEntry[] = [];
  for (const entry of timeline) {
    if (entry.kind === "thought") {
      out.push({ kind: "thought", id: entry.id, text: entry.text });
      continue;
    }
    if (!isExplorationActivity(entry.activity)) continue;
    const item: GroupableActivity = { ...entry.activity, id: entry.id };
    const last = out.at(-1);
    if (last && last.kind === "explorations") {
      out[out.length - 1] = { ...last, items: [...last.items, item] };
    } else {
      out.push({ kind: "explorations", id: `group-${entry.id}`, items: [item] });
    }
  }
  return out;
});
let thoughtsOpen = $state(true);

const blocksWithDelay = $derived.by(() => {
  let newInBatch = 0;
  return visibleBlocks.map((block) => {
    // Pre-render annotation markdown once per block so the template can
    // emit the annotation as a sibling grid item without each re-render
    // re-parsing markdown. Only code/diff/artifact blocks carry annotations.
    const renderedAnnotation =
      (block.type === "code" || block.type === "diff" || block.type === "artifact") &&
      block.annotation
        ? renderMarkdown(block.annotation)
        : null;
    if (hasBlockAnimated(prId, block.id)) {
      // Already animated in a previous mount — skip animation entirely
      return { block, delay: -1, renderedAnnotation };
    }
    // New block — assign staggered delay
    const delay = Math.min(newInBatch, STAGGER_CAP) * STAGGER_MS;
    newInBatch += 1;
    return { block, delay, renderedAnnotation };
  });
});

// Partition the per-block render entries by their parent semantic step so
// each chapter receives only its own atomic blocks. Falls back to a
// trailing "Diff analysis" bucket for any blocks that arrive before the
// chapter that owns them — should be impossible given the prompt's
// declaration order, but defensive against malformed streams.
const blocksBySection = $derived.by(() => {
  const map = new Map<number, typeof blocksWithDelay>();
  for (const entry of blocksWithDelay) {
    const idx = entry.block.semanticStepIndex ?? -1;
    const arr = map.get(idx);
    if (arr) {
      map.set(idx, [...arr, entry]);
    } else {
      map.set(idx, [entry]);
    }
  }
  return map;
});

// Hide chapters that exist in the DB but carry no atomic blocks yet. Two
// callers depend on this:
//   (a) The agent's currently-open chapter — there's a brief window after
//       `add_semantic_step` lands and before the first `add_diff_step` where
//       the section would render with just a heading. The bottom-of-feed
//       diff skeleton already signals "more incoming," so an empty chapter
//       above is noise.
//   (b) Defensive against a stalled agent that opened a chapter and never
//       filled it before the run ended. The completion gate rejects this
//       case server-side, but a cached partial may still have empty rows;
//       filtering keeps the UI honest.
const visibleSemanticSteps = $derived(
  semanticSteps.filter((s) => (blocksBySection.get(s.semanticStepIndex)?.length ?? 0) > 0),
);

// Pre-render the overview summary as a synthetic markdown block so it slots
// into the same WalkthroughSection grid as the Phase B chapters below. The
// id is fixed (one overview per walkthrough) and the chapter index is
// negative so it cannot collide with a real semantic_step_index.
const overviewSection = $derived({
  semanticStepIndex: -1,
  title: "Overview",
  summary: null,
} satisfies WalkthroughSemanticStep);
const overviewEntries = $derived.by(() => {
  if (summary === null) return [] as typeof blocksWithDelay;
  const overviewBlock: WalkthroughBlock = {
    type: "markdown",
    id: "overview-block",
    order: -1,
    phase: "overview",
    semanticStepIndex: -1,
    stepIndex: 0,
    content: summary,
  };
  return [
    {
      block: overviewBlock,
      delay: hasBlockAnimated(prId, overviewBlock.id) ? -1 : 0,
      renderedAnnotation: null,
    },
  ];
});
$effect(() => {
  if (summary !== null) markBlockAnimated(prId, "overview-block");
});

// Total chapters shown to the reader = the virtual overview chapter (when
// summary has arrived) + every visible Phase B chapter. Used by both the
// Overview chapter and the Phase B chapter loop for the "Ch N / M" eyebrow.
const totalChapters = $derived((summary !== null ? 1 : 0) + visibleSemanticSteps.length);

// Mirror the block-stagger logic for issue cards. Issue cards have their
// own CSS entrance animation (`issue-card-enter`), so without tracking they
// replay on every tab revisit the same way blocks used to.
const issueDelayById = $derived.by(() => {
  const map = new Map<string, number>();
  let newInBatch = 0;
  for (const issue of issues) {
    if (hasIssueAnimated(prId, issue.id)) {
      map.set(issue.id, -1);
      continue;
    }
    const delay = Math.min(newInBatch, STAGGER_CAP) * STAGGER_MS;
    newInBatch += 1;
    map.set(issue.id, delay);
  }
  return map;
});

// Side-effect animation tracking belongs in $effect, not inside $derived.by.
// Svelte 5 deriveds must be pure; impure deriveds can break reactive
// invalidation, which manifested as new walkthrough blocks / chapters
// failing to render after the first chapter until a click forced re-eval.
$effect(() => {
  for (const entry of blocksWithDelay) {
    if (entry.delay >= 0) {
      markBlockAnimated(prId, entry.block.id);
    }
  }
});
$effect(() => {
  for (const [issueId, delay] of issueDelayById) {
    if (delay >= 0) {
      markIssueAnimated(prId, issueId);
    }
  }
});

// ── Container animation gating ──────────────────────────────────────
// One-shot entrance animations for the stepper, content wrapper, summary,
// and issues section. Each element carries a `*--no-anim` class whose value
// is a reactive `$state` flag; the flag flips to `true` on `animationend`.
// After that, the class stays applied for the life of the component — so
// tab-switch display toggles, which in browsers normally restart CSS
// animations on subtrees re-entering the render tree, find `animation:
// none` and do nothing.
//
// Initial values come from the store so remounting the component for a PR
// the user has already viewed doesn't replay the first animation either.
// The effect below re-syncs from the store when the content identity
// changes (regenerate → new `streamStartedAt`, or the component is reused
// for a different PR → new `prId`), because `regenerate()` clears the
// trackers for fresh content to animate again.
// Seed from the tracker — `untrack` makes it explicit that we want the
// one-shot value at mount time. The $effect below handles any later
// reactive re-sync (regenerate, or the component instance being reused
// for a different PR — the latter won't happen with SvelteKit's route
// remount semantics, but we guard for it anyway).
let stepperAnimated = $state(untrack(() => hasContainerAnimated(prId, "stepper")));
let contentAnimated = $state(untrack(() => hasContainerAnimated(prId, "content")));
let issuesSectionAnimated = $state(untrack(() => hasContainerAnimated(prId, "issues-section")));

let lastSyncedFor: string | null = untrack(() => `${prId}:${streamStartedAt ?? "init"}`);
$effect(() => {
  const key = `${prId}:${streamStartedAt ?? "init"}`;
  if (key === lastSyncedFor) return;
  lastSyncedFor = key;
  stepperAnimated = hasContainerAnimated(prId, "stepper");
  contentAnimated = hasContainerAnimated(prId, "content");
  issuesSectionAnimated = hasContainerAnimated(prId, "issues-section");
});

type ContainerKey = "stepper" | "content" | "issues-section";

function lockContainerAnimation(key: ContainerKey, event: AnimationEvent): void {
  // Filter out bubbled events from descendants (issue-card-enter bubbles
  // up through .issues-section, block-slide-up through .walkthrough-content).
  if (event.target !== event.currentTarget) return;
  markContainerAnimated(prId, key);
  if (key === "stepper") stepperAnimated = true;
  else if (key === "content") contentAnimated = true;
  else issuesSectionAnimated = true;
}

// ── Issue → step navigation ─────────────────────────────────────────
// Issues carry `blockIds` — the block(s) that explain them. Clicking an
// issue card scrolls to the first linked block and briefly pulses it so
// the user visually connects the card they clicked to the block they
// landed on. Handled with a DOM lookup + requestAnimationFrame to avoid
// piping refs through every block component.

function stepNumberFor(blockId: string): number | null {
  // Use visibleBlocks so the step number matches the user-facing ordinal.
  // A legacy "## Overall Sentiment" block, when suppressed, must not shift
  // the numbering that the user sees in the rendered walkthrough.
  const idx = visibleBlocks.findIndex((b) => b.id === blockId);
  return idx >= 0 ? idx + 1 : null;
}

/**
 * Issue card tag — "Ch N · Step M" where N is the 1-based chapter index of
 * the block's parent semantic step (matching the chapter eyebrow in
 * WalkthroughSection) and M is the 1-based atomic position within that
 * chapter. Falls back to a flat "Step N" when the block has no parent
 * recorded (legacy data; shouldn't happen post-reset).
 */
function chapterTagFor(blockId: string): string | null {
  const block = visibleBlocks.find((b) => b.id === blockId);
  if (!block) return null;
  const semanticIdx = block.semanticStepIndex;
  const stepIdx = block.stepIndex;
  if (semanticIdx === undefined || stepIdx === undefined) {
    const n = stepNumberFor(blockId);
    return n !== null ? `→ Step ${n}` : null;
  }
  let chapterLabel: number;
  if (semanticIdx === -1) {
    // Virtual Overview chapter — always Ch 1
    chapterLabel = 1;
  } else {
    const pos = visibleSemanticSteps.findIndex((s) => s.semanticStepIndex === semanticIdx);
    // visibleSemanticSteps is 0-based; +1 for 1-based, +1 more to account for the Overview chapter
    chapterLabel = pos >= 0 ? pos + 2 : semanticIdx + 2;
  }
  return `→ Ch ${chapterLabel} · Step ${stepIdx + 1}`;
}

// ── Block → flagged-issue severity ─────────────────────────────────
// For each block referenced by at least one issue, pick the highest
// severity across all issues pointing at it. Used to render a colored dot
// to the left of the block so the reader can spot flagged steps while
// scrolling without having to cross-reference the Issues section.
const SEVERITY_RANK: Record<"info" | "warning" | "critical", number> = {
  info: 1,
  warning: 2,
  critical: 3,
};
const blockIssueSeverity = $derived.by(() => {
  const map = new Map<string, "info" | "warning" | "critical">();
  for (const issue of issues) {
    for (const bid of issue.blockIds) {
      const current = map.get(bid);
      if (!current || SEVERITY_RANK[issue.severity] > SEVERITY_RANK[current]) {
        map.set(bid, issue.severity);
      }
    }
  }
  return map;
});

// ── Selected issue (persistent block highlight) ─────────────────────
// When the reader clicks an issue card we keep a severity-colored outline
// on its linked block until another issue is selected. The brief
// `block-wrapper--highlighted` pulse used by other callers (ratings grid,
// cross-tab jumps) is intentionally not triggered here — the outline is
// the persistent signal, the scroll is the affordance.
let selectedIssueId = $state<string | null>(null);
const selectedIssue = $derived(
  selectedIssueId ? (issues.find((i) => i.id === selectedIssueId) ?? null) : null,
);
const selectedIssueBlockId = $derived(selectedIssue?.blockIds?.[0] ?? null);
const selectedIssueSeverity = $derived(selectedIssue?.severity ?? null);

// Drop the selection when we switch PRs so a stale id doesn't paint an
// outline on an unrelated block in the next walkthrough.
$effect(() => {
  void prId;
  selectedIssueId = null;
});

// Click-outside: any click that lands outside the selected step's block
// clears the highlight. Clicks inside the issue card list are exempt so
// the card's own onclick (which re-sets the selection) doesn't race with
// this listener — we'd otherwise clear and immediately re-set on every
// card click. Only registered while a selection is active.
$effect(() => {
  if (selectedIssueId === null) return;
  const blockId = selectedIssueBlockId;
  function onDocumentClick(e: MouseEvent): void {
    const target = e.target as Element | null;
    if (!target) return;
    if (blockId) {
      const selectedEl = document.getElementById(`step-${blockId}`);
      if (selectedEl?.contains(target)) return;
    }
    if (target.closest(".issue-card")) return;
    selectedIssueId = null;
  }
  document.addEventListener("click", onDocumentClick);
  return () => document.removeEventListener("click", onDocumentClick);
});

function selectIssue(issueId: string, blockId: string): void {
  selectedIssueId = issueId;
  // Defer scroll one frame: setting `selectedIssueId` may auto-expand a
  // collapsed parent section (see WalkthroughSection's $effect), and the
  // scroll math needs to read the post-expansion getBoundingClientRect to
  // land on the right spot.
  requestAnimationFrame(() => {
    const el = document.getElementById(`step-${blockId}`);
    if (!el || !scrollRoot) return;
    const containerRect = scrollRoot.getBoundingClientRect();
    const elRect = el.getBoundingClientRect();
    const offset = elRect.top - containerRect.top + scrollRoot.scrollTop - 16;
    scrollRoot.scrollTo({ top: offset, behavior: "smooth" });
  });
}

function jumpToStep(blockId: string): void {
  const el = document.getElementById(`step-${blockId}`);
  if (!el || !scrollRoot) return;
  // Compute offset relative to the scroll container so repeated clicks
  // always trigger a scroll (scrollIntoView is a no-op when already in view)
  const containerRect = scrollRoot.getBoundingClientRect();
  const elRect = el.getBoundingClientRect();
  const offset = elRect.top - containerRect.top + scrollRoot.scrollTop - 16;
  scrollRoot.scrollTo({ top: offset, behavior: "smooth" });
  // Defer the highlight class toggle to the next animation frame so the
  // forced reflow doesn't cancel the smooth scroll we just initiated
  requestAnimationFrame(() => {
    el.classList.remove("block-wrapper--highlighted");
    void el.offsetWidth;
    el.classList.add("block-wrapper--highlighted");
  });
}

// Stepper-cell click handler. Same scroll math as jumpToStep but no
// highlight pulse — the chapter sections (overview, diff, sentiment,
// scorecard) are large enough that a moving outline would be more
// visual noise than signal. The 16px breathing room above the anchor
// matches jumpToStep and the floating Top/Rating pills.
function jumpToSection(elementId: string): void {
  const el = document.getElementById(elementId);
  if (!el || !scrollRoot) return;
  const containerRect = scrollRoot.getBoundingClientRect();
  const elRect = el.getBoundingClientRect();
  const offset = elRect.top - containerRect.top + scrollRoot.scrollTop - 16;
  scrollRoot.scrollTo({ top: offset, behavior: "smooth" });
}

// Cross-tab jump: when another tab (e.g. Request Changes) calls
// jumpToWalkthroughBlock(), the store flips activeTab → 'walkthrough' and
// stashes the blockId. We consume it here once we're active + scrollRoot is
// bound. One rAF of slack lets the display swap (`display: none` → `display:
// contents`) settle so getBoundingClientRect returns real geometry.
$effect(() => {
  const pendingBlockId = getPendingWalkthroughBlockJump();
  if (!pendingBlockId) return;
  if (!isActive || !scrollRoot) return;
  requestAnimationFrame(() => {
    jumpToStep(pendingBlockId);
    clearPendingWalkthroughBlockJump();
  });
});

onMount(() => {
  initHighlighter();
});

$effect(() => {
  const mode = selectedMode;
  if (hydratedForMode === mode) return;
  hydratedForMode = mode;
  hydrating = true;
  // Seed a loading entry synchronously so the UI renders the skeleton
  // while we check the cache. Without this, the derived state resolves
  // to defaults (no summary, not streaming, no error) and the template
  // briefly shows the "No walkthrough data received" empty state.
  prepareEntry(prId, mode);
  // Try to hydrate instantly from the JSON cache endpoint. On a hit the
  // walkthrough renders immediately with no SSE round-trip. On a miss
  // we fall back to the debounced SSE stream — the debounce is intentional
  // for uncached PRs so quickly arrowing through the PR list doesn't
  // trigger spurious AI generations.
  hydrateFromCache(prId, { mode }).then(
    () => {
      hydrating = false;
    },
    () => {
      hydrating = false;
    },
  );
});

onDestroy(() => {
  if (elapsedTimer) clearInterval(elapsedTimer);
  if (stallTimer) clearInterval(stallTimer);
  if (walkthroughDebounce) clearTimeout(walkthroughDebounce);
  stopClonePoll(prId);
});

// ── Clone-in-progress auto-retry ────────────────────────────────────
// When the server rejects the walkthrough because the repo is still
// cloning, we used to rely solely on an SSE-delivered `cloneStatus === 'ready'`
// update to auto-retry. That's fragile: missed SSE messages, server restarts
// that reset clone state to 'pending', and outright clone failures would
// leave the UI permanently stuck on "Cloning repository…". Now we start a
// poller against `GET /api/repos/:id/clone-status` that is authoritative for
// all terminal states (ready/error/pending) regardless of SSE delivery. The
// SSE fast-path still runs: if the repositories store already reports 'ready'
// (from an SSE broadcast) we stream immediately without waiting for the next
// poll tick.
$effect(() => {
  if (!cloneInProgress || !cloneRepoId) return;
  if (cloneRepo?.cloneStatus === "ready") {
    void startWalkthrough(prId, selectedMode);
    return;
  }
  void pollCloneUntilResolved(prId, cloneRepoId, selectedMode);
  return () => stopClonePoll(prId);
});

// ── Retry-clone button (escape hatch) ────────────────────────────────
// Visible when the UI is stuck in the clone-in-progress state. Hits the
// server's `/retry-clone` endpoint, which resets the repo's clone state and
// kicks off a fresh clone, then restarts the poller so the UI un-sticks
// regardless of whether the SSE fast-path fires.
let retryingClone = $state(false);
async function handleRetryClone(): Promise<void> {
  if (!cloneRepoId || retryingClone) return;
  const repoId = cloneRepoId;
  retryingClone = true;
  try {
    await fetch(`${API_BASE_URL}/api/repos/${repoId}/retry-clone`, {
      method: "POST",
      headers: authHeaders(),
    });
    void pollCloneUntilResolved(prId, repoId, selectedMode);
  } finally {
    retryingClone = false;
  }
}

// ── Regenerate ──────────────────────────────────────────────────────
function handleRegenerate(): void {
  regenerate(prId, selectedMode);
}
</script>

<div class="walkthrough">
	{#if !streamError && stepperVisible}
		<!-- Persistent chapters stepper. Replaces the old A→B→C→D dot indicator.
		     Lives outside the if/else ladder so it stays mounted as the streaming
		     view transitions from the loading skeleton (pre-summary) into the
		     content view (post-summary), and stays mounted after generation
		     completes as a navigation aid. `stepperAnimated` gates the one-shot
		     entrance animation so a tab revisit doesn't replay the fade. During
		     streaming, the active cell is driven by `lastCompletedPhase`: 'none'
		     → Overview, 'A' → Diff, 'B' → Sentiment, 'C' → Rating. After streaming,
		     all cells with content become clickable jumps to their section. -->
		<div
			class="walkthrough-stepper-header"
			class:walkthrough-stepper-header--no-anim={stepperAnimated}
			onanimationend={(e) => lockContainerAnimation('stepper', e)}
		>
			<div
				class="chapter-stepper"
				role="progressbar"
				aria-label="Walkthrough chapters"
				aria-valuenow={activeChapterIndex + 1}
				aria-valuemin={1}
				aria-valuemax={CHAPTERS.length}
			>
				{#each CHAPTERS as chapter, i (chapter.id)}
					{@const active = isStreaming && i === activeChapterIndex}
					{@const done = isStreaming && i < activeChapterIndex}
					{@const queued = isStreaming && i > activeChapterIndex}
					{@const available = chapterAvailability[i] ?? false}
					{@const clickable = !active && available}
					<button
						type="button"
						class="chapter-cell"
						class:chapter-cell--active={active}
						class:chapter-cell--done={done}
						class:chapter-cell--queued={queued}
						class:chapter-cell--available={!isStreaming && available}
						class:chapter-cell--unavailable={!isStreaming && !available}
						class:chapter-cell--clickable={clickable}
						disabled={!clickable}
						aria-label={clickable ? `Jump to ${chapter.label}` : chapter.label}
						onclick={clickable ? () => jumpToSection(chapter.targetId) : undefined}
					>
						<div class="chapter-eyebrow">Step {String(i + 1).padStart(2, '0')}</div>
						{#if active}
							<div class="chapter-active-layout">
								<div class="chapter-title">{chapter.label}</div>
								<div class="chapter-active-row">
							<Dotmatrix variant={chapter.spinner} active={active} />
									{#if recentExplorationSteps.length > 0}
										<div class="chapter-tool-calls">
											{#each recentExplorationSteps.slice(-2) as { step, ordinal }, i (ordinal)}
												<div
													class="chapter-tool-call"
													style="top: {i * TOOL_CALL_ROW_H}px"
													in:gsapFadeY={{ y: TOOL_CALL_ROW_H, duration: tokens.smooth }}
													out:gsapFadeY={{ y: -TOOL_CALL_ROW_H, duration: tokens.quick }}
												>
													<span class="chapter-tool-call-tool">{step.toolName}</span>
													<span class="chapter-tool-call-desc">{step.summary}</span>
												</div>
											{/each}
										</div>
									{:else}
										<span>{chapter.activeBlurb}</span>
									{/if}
								</div>
							</div>
						{:else}
							<div class="chapter-title-row">
								<div class="chapter-title">{chapter.label}</div>
							</div>
							<div class="chapter-body">
								<div class="chapter-blurb">{chapter.blurb}</div>
							</div>
						{/if}
					</button>
				{/each}
			</div>
		</div>
	{/if}

	{#if streamError && !summary && blocks.length === 0}
		<div class="walkthrough-empty">
			{#if explorationSteps.length > 0}
				<div class="exploration-feed exploration-feed--error">
					{#each explorationSteps.slice(-6) as step, i (i)}
						<div class="exploration-item">
							<span class="exploration-tool">{step.toolName}</span>
							<span class="exploration-desc">{step.summary}</span>
						</div>
					{/each}
				</div>
			{/if}
			<p class="loading-text">Walkthrough generation stopped. Check the notification for details.</p>
			<Button variant="outline" size="lg" style="cursor: pointer;" onclick={handleRegenerate}>
				<RefreshCw size={16} weight="fill" />
				Try again
			</Button>
		</div>
	{:else if cloneInProgress && !summary && blocks.length === 0}
		<!-- Clone-in-progress state: show indeterminate progress bar + Retry
		     escape hatch. The poller set up in the $effect above drives this
		     view to a terminal state (startWalkthrough on 'ready', or a
		     streamError branch on 'error'/'pending'), but a stuck server or
		     network partition can still happen — the Retry button gives the
		     user an explicit way out. When cloneRepoId is somehow null (SSE
		     error event didn't carry it), we can't address the retry at a
		     specific repo, so we fall back to a generic Try again that
		     regenerates the walkthrough. -->
		<div class="walkthrough-empty">
			{#if !cloneRepoId}
				<AlertTriangle size={20} weight="fill" />
				<p class="loading-text">Couldn't identify the repository that was cloning.</p>
			{:else}
				<div class="clone-progress-container">
					<p class="loading-text">Cloning repository…</p>
					<Progress indeterminate class="clone-progress-bar" />
					<p class="loading-subtext">The walkthrough will start automatically when cloning completes.</p>
					<Button
						variant="outline"
						size="lg"
						style="cursor: pointer;"
						disabled={retryingClone}
						onclick={handleRetryClone}
					>
						<RefreshCw size={16} weight="fill" />
						Retry clone
					</Button>
				</div>
			{/if}
		</div>
	{:else if !isStreaming && !summary && blocks.length === 0 && !streamError && !cloneInProgress && !hydrating}
		<div class="walkthrough-empty">
			<p class="loading-text">No walkthrough generated yet for this PR.</p>
		</div>
	{:else if !summary && blocks.length === 0 && sentiment === null && ratings.length === 0 && isStreaming}
		<!-- Loading state: skeleton + exploration feed. Only shown before the
		     first MCP write lands. The moment Phase A's summary (or any later
		     phase's content) arrives, we fall through to the content branch
		     below so subsequent MCP writes — diff steps, sentiment, ratings —
		     render incrementally as they're committed.
		     The chapters stepper above is rendered as a sibling outside this
		     ladder, so it stays mounted across the loading → content transition. -->
		<div class="walkthrough-loading">
			<!-- Tool calls render inside the active chapter cell of the
			     stepper above (`.chapter-tool-calls`); we don't duplicate
			     them in a separate exploration section here. -->

			<!-- The "Reviewing..." shimmer is deferred to the content branch
			     (showDiffSkeleton) so it only appears after Phase A lands. -->

			<!-- Empty rating grid, mounted from the start of generation so the
			     reviewer sees the 9-axis scorecard up front and watches cells
			     resolve as Phase D unfolds. `forceShow` opts out of the
			     hide-when-empty guard inside WalkthroughRatingsGrid (which
			     stays in place for cached pre-scorecard walkthroughs). The
			     same component is also rendered post-summary by the content
			     branch below — Svelte unmounts this instance and remounts
			     there, but the visual is identical so the swap is seamless. -->
			<div id="walkthrough-rating" class="sentiment-scorecard">
				<WalkthroughRatingsGrid
					{ratings}
					blocks={visibleBlocks}
					onJump={jumpToStep}
					forceShow={true}
				/>
			</div>
		</div>
	{:else if summary}
		<!-- Landing page content -->
		<div
			class="walkthrough-content"
			class:walkthrough-content--no-anim={contentAnimated}
			onanimationend={(e) => lockContainerAnimation('content', e)}
		>
			<!-- Issues — bucketed by severity (Critical → Warning → Info) so the
			     reviewer's eye lands on blockers before nice-to-knows. The overall
			     "N issues flagged" line is preserved as the section header; each
			     bucket then carries its own labeled sub-header with a count. -->
			{#if issues.length > 0}
				<div
					class="issues-section"
					class:issues-section--no-anim={issuesSectionAnimated}
					onanimationend={(e) => lockContainerAnimation('issues-section', e)}
				>
					<div class="issues-header">
						<AlertTriangle size={13} weight="fill" />
						<span>{issues.length} issue{issues.length !== 1 ? 's' : ''} flagged</span>
					</div>
					<div class="issues-groups">
						{#each issueGroups as group (group.severity)}
							<div class="issues-group">
								<div class="issues-group-header issues-group-header--{group.severity}">
									<span class="issues-group-dot"></span>
									<span class="issues-group-label">{group.label}</span>
									<span class="issues-group-count">{group.issues.length}</span>
								</div>
								<div class="issues-list">
									{#each group.issues as { issue, globalIndex } (issue.id)}
										{@const targetBlockId = issue.blockIds?.[0] ?? null}
										{@const stepN = targetBlockId ? stepNumberFor(targetBlockId) : null}
										{@const chapterTag = targetBlockId ? chapterTagFor(targetBlockId) : null}
										<!-- Gate clickability on the referenced block actually existing in
										     the current render. `blockIds` can point to a block that isn't in
										     `blocks` (kept issues after regenerate, or a mid-stream race
										     between the issue arriving and its block rendering) — in which
										     case jumpToStep would silently no-op and the click would feel
										     broken. stepN is null whenever the lookup fails, which catches
										     both a missing targetBlockId and an id that doesn't resolve. -->
										{#if stepN !== null && targetBlockId}
											<IssueCard
												{issue}
												clickable
												onclick={() => selectIssue(issue.id, targetBlockId)}
												stepTag={chapterTag ?? `→ Step ${stepN}`}
												animationDelay="{Math.min(globalIndex, 6) * 50}ms"
												noAnim={issueDelayById.get(issue.id) === -1}
												onfileclick={(filePath, line) => jumpToDiffLine(filePath, line)}
												hideFileBadge={true}
											/>
										{:else}
											<IssueCard
												{issue}
												stepTag={null}
												animationDelay="{Math.min(globalIndex, 6) * 50}ms"
												noAnim={issueDelayById.get(issue.id) === -1}
												onfileclick={(filePath, line) => jumpToDiffLine(filePath, line)}
												hideFileBadge={true}
											/>
										{/if}
									{/each}
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/if}

			<!-- Body — every chapter renders as a collapsible WalkthroughSection.
			     The Phase A summary becomes the virtual first chapter ("Overview");
			     the Phase B semantic_steps follow in declaration order. Each
			     section owns its atomic blocks via `semanticStepIndex`; the
			     WalkthroughSection wrapper uses `display: contents` so per-block
			     grid placement (cols 2/3/5) still resolves against this `.blocks`
			     grid. Empty Phase B chapters are filtered out (see
			     `visibleSemanticSteps`) so an open-but-unfilled chapter doesn't
			     render as a bare heading. Phase C (sentiment) and Phase D
			     (scorecard) live in their own cards below the loop. -->
			<div class="blocks">
			<WalkthroughSection
				id="walkthrough-overview"
				section={overviewSection}
				entries={overviewEntries}
				{blockIssueSeverity}
				{selectedIssueBlockId}
				{selectedIssueSeverity}
				chapterNumber={1}
				chapterCount={totalChapters}
			/>
			{#each visibleSemanticSteps as section, sectionIdx (section.semanticStepIndex)}
				<WalkthroughSection
					id={sectionIdx === 0 ? 'walkthrough-diff' : undefined}
					{section}
					entries={blocksBySection.get(section.semanticStepIndex) ?? []}
					{blockIssueSeverity}
					{selectedIssueBlockId}
					{selectedIssueSeverity}
					chapterNumber={sectionIdx + 2}
					chapterCount={totalChapters}
				/>
			{/each}

		<!-- Diff-analysis skeleton: visible from Phase A→C. Mirrors the recap
		     pattern (RecapDetail.svelte): the "Reviewing…" shimmer is a
		     Collapsible trigger gating the model's reasoning text. When the
		     toggle is closed, the activity stack below shows only the
		     consolidated exploration groups (shimmer + odometer counts). When
		     open, the stack switches to a chronological view that interleaves
		     thought blocks with the same grouped tool calls — reads as a
		     timeline. MCP write tools are filtered at the derived layer. -->
		{#if showDiffSkeleton}
			<div class="block-group">
				<span class="block-step-dot" aria-hidden="true"></span>
				<div class="block-wrapper block-wrapper--no-anim walkthrough-skeleton">
					<ThoughtsReveal
						bind:open={thoughtsOpen}
						triggerClass="walkthrough-phase-trigger"
						ariaLabel="Reviewing. Toggle streamed thoughts."
						metaLabel=""
					>
						{#snippet prefix()}
							<Shimmer class="text-sm" aria-label="Reviewing">Reviewing...</Shimmer>
						{/snippet}
						{#if interleavedEntries.length > 0}
							<div class="walkthrough-activity-stack">
								{#each interleavedEntries as entry, entryIdx (entry.id)}
									{#if entry.kind === 'thought'}
										<div class="walkthrough-activity-entry" data-kind="thought">
											<div class="walkthrough-inline-thought prose prose-sm">
												{@html renderMarkdown(entry.text)}
											</div>
										</div>
									{:else}
										<div class="walkthrough-activity-entry" data-kind="explorations">
											<ToolActivityGroup
												items={entry.items}
												active={entryIdx === interleavedEntries.length - 1}
												defaultOpen={false}
											/>
										</div>
									{/if}
								{/each}
							</div>
						{:else}
							<p class="walkthrough-thought-empty">
								No streamed thoughts yet. Tool calls will appear here as they happen.
							</p>
						{/if}
					</ThoughtsReveal>
				</div>
			</div>
		{/if}

			<!-- Phase C / D conclusion: sentiment card above the scorecard.
			     Rendered as a single grid item (block-group--sentiment-stack)
			     so the pair spans the content column cleanly regardless of how
			     many diff steps preceded it. During streaming we keep the
			     scorecard mounted (empty queued cells) so the reviewer has a
			     stable destination for Phase D content. -->
			{#if sentiment !== null || ratings.length > 0 || isStreaming}
				<div class="block-group block-group--sentiment-stack">
					{#if sentiment !== null}
						<div id="walkthrough-sentiment" class="sentiment-card" aria-label="Overall sentiment">
							<div class="sentiment-card-header">
								<h3 class="sentiment-card-title">Overall Sentiment</h3>
							</div>
							<div class="sentiment-card-body prose prose-sm" use:mermaidDiagrams={getResolvedTheme()}>{@html renderedSentiment}</div>
						</div>
					{/if}
					{#if ratings.length > 0 || isStreaming}
						<!-- During streaming, render the grid even before the first
						     axis arrives so the reviewer has a place for ratings
						     to land in (cells start in the queued state). After
						     streaming, fall back to the original guard so cached
						     pre-scorecard walkthroughs stay clean. -->
						<div id="walkthrough-rating" class="sentiment-scorecard">
							<WalkthroughRatingsGrid
								{ratings}
								blocks={visibleBlocks}
								onJump={jumpToStep}
								forceShow={isStreaming}
							/>
						</div>
					{/if}
				</div>
			{/if}
			</div>

			<!-- Scorecard lives inline under the Overall Sentiment card now
			     (see the .blocks loop above). No end-of-walkthrough rendering. -->

			<!-- Mono footer — mirrors the recap detail footer so the two views
			     share one attribution language. Dropped the avatar/badge/bold
			     so the line is pure mono text with `·` separators. -->
			{#if footerParts.length > 0}
				<footer class="walkthrough-footer">
					<span>{footerParts.join(" · ")}</span>
				</footer>
			{/if}
		</div>

	{/if}
</div>

<style>
	.walkthrough {
		display: flex;
		flex-direction: column;
		background: var(--color-bg-primary);
	}

	.walkthrough-content {
		/* 6-col grid that centres the content column within the MAIN AREA,
		   so the content re-centres whenever either flanking pane (sidebar
		   or right chat panel) toggles. Both panes are real grid columns in
		   AppShell.svelte, so opening either shrinks the main-area — and the
		   grid container here (`.review-content`, container-type: inline-size)
		   shrinks with it. `100%`/`50%` therefore always track the visible
		   main-area width, which is exactly what we centre against.

		   col 1 = max(24px, min(50% - 458px, 100% - 1312px))
		     - 50% - 458px : the col_1 width that places the content column's
		         centre at the main-area centre (50%). Content x-centre within
		         the grid = col_1 + 48 + 410; setting that to 50% gives
		         col_1 = 50% - 458. Because `%` is relative to the main-area
		         width, this stays centred on every sidebar/right-panel toggle.
		     - 100% - 1312px : the largest col_1 that still lets the rail end
		         at exactly 100% - 24 (24px right gutter inside main-area).
		         Binds on narrower main-areas where pure centring would push
		         rail-plus-content past the right gutter.
		     min() picks whichever binds. They cross at a main-area width of
		         1708; above, centring wins; below, rail pinning wins. Floor
		         of 24px keeps a minimum left gutter.
		   col 2 = 48        (severity-dot gutter)
		   col 3 = 820       (content)
		   col 4 = 40        (content ↔ rail gap)
		   col 5 = 380       (annotation rail)
		   col 6 = 1fr, ≥ 24 (right gutter; absorbs excess past the rail)

		   Geometric min of main-area width = 24 + 48 + 820 + 40 + 380 + 24
		   = 1336. Below that the side-by-side grid physically doesn't fit;
		   the @container rule at the bottom falls through to a stacked
		   layout. The breakpoint is on main-area width (100%, via
		   container-type: inline-size on .review-content) so the collapse
		   triggers only when a flanking pane has eaten enough room to matter. */
		display: grid;
		grid-template-columns:
			max(24px, min(calc(50% - 458px), calc(100% - 1312px)))
			48px
			minmax(0, 820px)
			40px
			380px
			minmax(24px, 1fr);
		padding: 28px 0;
		animation: fadeIn var(--duration-smooth) var(--ease-standard) 60ms both;
	}

	/* Single-column sections live in the content column (col 3). */
	.walkthrough-content > .issues-section,
	.walkthrough-content > .walkthrough-footer,
	.walkthrough-content > :global([data-slot="separator"]) {
		grid-column: 3;
	}

	/* Mono attribution footer — mirrors `.recap-detail-footer` in
	   RecapDetail so walkthrough + recap views share one attribution
	   pattern. Lives at the bottom of `.walkthrough-content`, lands in
	   col 3 via the grid-column rule above. */
	.walkthrough-footer {
		margin-top: 1.5rem;
		padding-top: 0.5rem;
		border-top: 1px solid var(--color-border-subtle);
		font-size: 0.75rem;
		color: var(--color-text-muted);
		font-family: var(--font-mono);
		letter-spacing: 0.01em;
	}

	/* Suppress the entrance animation on tab revisits. Paired with the
	   `walkthrough-content--no-anim` class toggled from the component script
	   after the first `animationend` — without this, browsers restart the
	   animation when the subtree re-enters the render tree after the tab's
	   `display: none` is lifted. */
	.walkthrough-content--no-anim {
		animation: none;
		opacity: 1;
	}

	/* Pane-anchored centering for the empty state. Absolutely positioned
	   inside the nearest positioned ancestor (`.review-page` from the route
	   shell), so the button lands at the dead centre of the main pane
	   regardless of what's rendered above it (page title, dimmed stepper).
	   Without `position: absolute` the empty state sits in normal flow under
	   the stepper and its 60vh min-height pushes the centred content below
	   the pane midline.

	   `pointer-events: none` on the wrapper + `auto` on direct children lets
	   the empty area pass clicks through to the stepper cells underneath
	   (they're disabled in this state, but it keeps the layer non-blocking). */
	.walkthrough-empty {
		position: absolute;
		inset: 0;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 12px;
		padding: 24px;
		pointer-events: none;
	}

	/* `:global(*)` — children include a shadcn Button whose root carries a
	   different Svelte scope hash, so a scoped `> *` rule would skip it. */
	.walkthrough-empty > :global(*) {
		pointer-events: auto;
	}

	/* Loading and stepper-header use the SAME 6-col grid as
	   `.walkthrough-content` so their inner content lands in col 3 — the
	   820 content column — exactly where the streamed walkthrough blocks
	   will render. A plain max-width: 900; margin-inline: auto would NOT
	   align with col 3 because the asymmetric grid makes col 3 centered
	   in the viewport but cols 3–5 (including rail) are shifted right, so
	   a viewport-centered box lands offset from where content actually goes.
	   Grid here guarantees pixel-identical alignment with the eventual
	   walkthrough content column. */
	.walkthrough-loading {
		display: grid;
		grid-template-columns:
			max(24px, min(calc(50% - 458px), calc(100% - 1312px)))
			48px
			minmax(0, 820px)
			40px
			380px
			minmax(24px, 1fr);
		padding: 28px 0;
		row-gap: 20px;
	}

	/* Each skeleton / status-bar / exploration-feed lands in col 3 (the 820
	   content column). `:global(*)` because child components (e.g. <Shimmer>)
	   emit elements without the parent's Svelte scope hash. */
	.walkthrough-loading > :global(*) {
		grid-column: 3;
	}

	/* ── Persistent chapters stepper header ─────────────────────────────
	   Replaces the old A→B→C→D dot indicator. Stays mounted across the
	   loading → content transition so the user keeps a map of where the
	   walkthrough is in the pipeline. Aligned to col 3 of the same 6-col
	   grid as `.walkthrough-loading` and `.walkthrough-content`. */

	.walkthrough-stepper-header {
		display: grid;
		grid-template-columns:
			max(24px, min(calc(50% - 458px), calc(100% - 1312px)))
			48px
			minmax(0, 820px)
			40px
			380px
			minmax(24px, 1fr);
		padding: 24px 0 4px;
		animation: fadeIn var(--duration-smooth) var(--ease-standard) both;
	}

	.walkthrough-stepper-header > * {
		grid-column: 3;
	}

	.walkthrough-stepper-header--no-anim {
		animation: none;
		opacity: 1;
	}

	/* When the stepper header is present, tighten the top padding of the
	   following loading/content block so the two read as one continuous
	   region instead of two stacked panels with a big gap. */
	.walkthrough-stepper-header + .walkthrough-loading,
	.walkthrough-stepper-header + .walkthrough-content {
		padding-top: 14px;
	}

	/* ── Chapters stepper ────────────────────────────────────────────────
	   Four-cell horizontal grid. Active cell: 2px accent top rule, italic
	   serif eyebrow, big serif title, body row of {dot-matrix spinner +
	   "reading" verb + live mono file path}. Past/queued cells: same title
	   with a static blurb under it — no "done" affordance, just absence of
	   the active treatment. */

	.chapter-stepper {
		display: grid;
		grid-template-columns: repeat(4, 1fr);
		column-gap: 16px;
	}

	.chapter-cell {
		/* Reset button defaults — the cell is rendered as a <button> so it can
		   participate in tab order and fire onclick when clickable. Inheriting
		   the surrounding type styles keeps the visual output identical to the
		   prior <div>-based markup. */
		appearance: none;
		background: transparent;
		border: none;
		border-radius: 0;
		font: inherit;
		color: inherit;
		text-align: left;
		display: block;
		width: 100%;

		min-width: 0;
		padding: 10px 0 0;
		/* `--color-border` (not `--color-border-subtle`): in dark mode the
		   `subtle` token collapses onto the tertiary surface and the rule
		   becomes invisible. Border is a tier up — visible against
		   `--color-bg-primary` in both light and dark themes. */
		border-top: 2px solid var(--color-border);
		transition: border-color var(--duration-smooth) var(--ease-soft), opacity var(--duration-smooth) var(--ease-soft),
			transform var(--duration-quick) var(--ease-soft), background-color var(--duration-quick) var(--ease-soft);
		cursor: default;
	}

	.chapter-cell:disabled {
		cursor: default;
	}

	.chapter-cell--active {
		border-top-color: var(--color-accent);
	}

	.chapter-cell--done {
		border-top-color: var(--color-accent);
		opacity: 0.5;
	}

	.chapter-cell--queued {
		opacity: 0.35;
	}

	/* ── Navigation mode (post-streaming) ─────────────────────────────────
	   Once generation finishes, the stepper persists as a chapter index for
	   quick jumps to any section. Chapters whose content was written get a
	   highlighted top rule + clickable hover/focus treatment; chapters that
	   never wrote (e.g., generation aborted before Phase D) stay muted. */

	.chapter-cell--available {
		border-top-color: var(--color-accent);
	}

	.chapter-cell--unavailable {
		opacity: 0.35;
	}

	.chapter-cell--clickable {
		cursor: pointer;
	}

	/* Done cells (already-completed phases during streaming) drop to 0.5
	   opacity by default to read as "past." Bump opacity on hover so the
	   click affordance is unambiguous when the user reaches for one. */
	.chapter-cell--clickable.chapter-cell--done:hover {
		opacity: 1;
	}

	.chapter-cell--clickable:hover .chapter-title {
		color: var(--color-accent);
	}

	.chapter-cell--clickable:hover .chapter-blurb {
		color: var(--color-text-secondary);
	}

	.chapter-cell--clickable:focus-visible {
		outline: 2px solid var(--color-accent);
		outline-offset: 2px;
		border-radius: 4px;
	}

	.chapter-cell--clickable:active {
		transform: translateY(1px);
	}

	.chapter-eyebrow {
		font-family: 'Newsreader', Georgia, serif;
		font-style: italic;
		font-size: 11.5px;
		font-weight: 500;
		letter-spacing: 0.3px;
		color: var(--color-text-muted);
		margin-bottom: 2px;
		white-space: nowrap;
		transition: color var(--duration-smooth) var(--ease-soft);
	}

	.chapter-cell--active .chapter-eyebrow,
	.chapter-cell--done .chapter-eyebrow,
	.chapter-cell--available .chapter-eyebrow {
		color: var(--color-accent);
	}

	.chapter-active-layout {
		display: flex;
		flex-direction: column;
		gap: 4px;
		min-width: 0;
		margin-bottom: 6px;

	}

	/* inactive path only */
	.chapter-title-row {
		display: flex;
		align-items: center;
		gap: 7px;
		margin-bottom: 6px;
		min-width: 0;
	}

	.chapter-title {
		font-family: 'Newsreader', Georgia, serif;
		font-size: 18px;
		font-weight: 500;
		letter-spacing: -0.012em;
		line-height: 1.05;
		color: var(--color-text-primary);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		transition: color var(--duration-smooth) var(--ease-soft);
	}



	.chapter-body {
		min-height: 32px;
	}

	.chapter-active-row {
		display: flex;
		align-items: center;
		gap: 6px;
		font-size: 10px;
		color: var(--color-accent);
		min-width: 0;
	}

	.chapter-tool-calls {
		position: relative;
		flex: 1;
		height: 28px; /* 2 × 14px rows, fixed — prevents layout shift during transitions */
		min-width: 0;
		overflow: hidden;
	}

	.chapter-tool-call {
		position: absolute;
		left: 0;
		right: 0;
		display: flex;
		gap: 6px;
		min-width: 0;
		/* `top` is deliberate over `transform: translateY`: Svelte's `fly` enter
		   transition (used inline) writes inline `transform`, and a base-class
		   transform would compose unpredictably with it. The animated property
		   is bounded to ±14px so the layout cost is trivial. */
		transition: top var(--duration-smooth) var(--ease-standard);
	}

	.chapter-tool-call-tool {
		color: var(--color-accent);
		font-weight: 500;
		flex-shrink: 0;
	}

	.chapter-tool-call-desc {
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		min-width: 0;
		color: var(--color-text-muted);
	}

	.chapter-blurb {
		font-size: 10.5px;
		line-height: 1.35;
		color: var(--color-text-muted);
		white-space: nowrap;
		overflow: hidden;
		transition: color var(--duration-smooth) var(--ease-soft);
		text-overflow: ellipsis;
	}

	/* ── Exploration feed (error branch only) ────────────────────────────
	   The active generating UI surfaces tool calls inside the chapter cell
	   itself (`.chapter-tool-calls`). The error branch still renders the
	   last few tool calls so a failed generation gives the user a trace
	   of what the agent attempted before the abort. */

	.exploration-feed {
		width: 100%;
		display: flex;
		flex-direction: column;
		gap: 3px;
		overflow: hidden;
		padding: 10px 12px;
		background: var(--color-bg-secondary);
		border-radius: 6px;
		border: 1px solid var(--color-border);
	}

	.exploration-item {
		display: flex;
		gap: 8px;
		font-size: 11px;
		font-family: var(--font-mono, monospace);
		color: var(--color-text-muted);
		animation: fadeIn var(--duration-smooth) var(--ease-out-expo);
		line-height: 1.5;
	}

	.exploration-tool {
		color: var(--color-accent);
		flex-shrink: 0;
		min-width: 36px;
		font-weight: 500;
	}

	.exploration-desc {
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.exploration-feed--error {
		opacity: 0.5;
		margin-bottom: 8px;
		max-width: 520px;
	}

	/* Overview is rendered as the virtual first chapter inside the .blocks
	   grid (see the template), so it picks up the standard chapter eyebrow,
	   heading, and markdown-block styling. No standalone summary styling is
	   needed at this layer. */

	/* ── Issues layout ───────────────────────────────────────────────── */

	.issues-section {
		margin-top: 20px;
		margin-bottom: 4px;
		display: flex;
		flex-direction: column;
		gap: 10px;
		animation: content-enter var(--duration-ceremonial-medium) var(--ease-standard) 0.15s both;
	}

	/* Tab-revisit override — see .walkthrough-content--no-anim for why. */
	.issues-section--no-anim {
		animation: none;
		opacity: 1;
		filter: none;
		transform: none;
	}

	.issues-header {
		display: flex;
		align-items: center;
		gap: 6px;
		font-size: 11px;
		font-weight: 600;
		color: var(--color-text-muted);
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.issues-groups {
		display: flex;
		flex-direction: column;
		gap: 14px;
	}

	.issues-group {
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	.issues-group-header {
		display: flex;
		align-items: center;
		gap: 6px;
		font-size: 10px;
		font-weight: 600;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		color: var(--color-text-secondary);
	}

	.issues-group-dot {
		width: 6px;
		height: 6px;
		border-radius: 50%;
		background: var(--severity-color, var(--color-text-muted));
	}

	.issues-group-label {
		color: var(--severity-color, var(--color-text-secondary));
	}

	.issues-group-count {
		color: var(--color-text-muted);
		font-variant-numeric: tabular-nums;
		font-weight: 500;
	}

	.issues-group-header--critical { --severity-color: var(--color-danger); }
	.issues-group-header--warning { --severity-color: var(--color-warning); }
	.issues-group-header--info { --severity-color: var(--color-accent); }

	.issues-list {
		display: flex;
		flex-direction: column;
		gap: 8px;
	}

	/* ── Blocks ──────────────────────────────────────────────────────── */

	/* Give every Separator inside the walkthrough content breathing room */
	.walkthrough-content :global([data-slot="separator"]) {
		margin: 28px 0;
	}

	.blocks {
		/* Blocks spans the full width of the walkthrough-content grid and
		   re-declares the same column tracks so its .block-wrapper (col 3) and
		   .block-annotation (col 5) align pixel-for-pixel with the single-column
		   sections above. Since .blocks spans `1 / -1` of its parent, its total
		   width equals the parent's total width, so the minmax tracks resolve
		   identically to the parent's — no subgrid needed. */
		display: grid;
		grid-column: 1 / -1;
		grid-template-columns:
			max(24px, min(calc(50% - 458px), calc(100% - 1312px)))
			48px
			minmax(0, 820px)
			40px
			380px
			minmax(24px, 1fr);
		row-gap: 20px;
		margin-top: 20px;
		grid-auto-flow: row;
	}

	/* Transparent wrapper: .block-wrapper and .block-annotation become direct
	   grid items of .blocks via display:contents. Explicit grid-column
	   assignments below are what force each item into its correct column —
	   without them, a block without an annotation would let the next block's
	   wrapper slip into col 2 via auto-placement. */
	.block-group {
		display: contents;
	}

	.block-group > .block-wrapper {
		grid-column: 3;
	}

	/* Sentiment pairing: stack the sentiment card above the scorecard in the
	   content column only. `display: flex` here escapes `display: contents`,
	   so the whole group becomes a single grid item that can declare grid-column.
	   With the grid now spanning the full viewport (not a 1264 container),
	   spanning `1 / -1` would stretch the 3×3 scorecard across 2000+px on
	   wide monitors, so we confine to col 3. */
	.block-group--sentiment-stack {
		display: flex;
		flex-direction: column;
		gap: 16px;
		align-items: stretch;
		grid-column: 3;
		/* Extra breathing room above the Phase C / D conclusion so the body
		   blocks feel closed out before the sentiment card appears. The old
		   layout achieved this with a <Separator /> inside the loop; the new
		   layout places the pair outside the loop, so we lean on margin. */
		margin-top: 16px;
		padding-top: 16px;
		border-top: 1px solid var(--color-border);
	}

	.block-group--sentiment-stack > :global(*) {
		/* Each child takes full width. `min-width: 0` keeps long monospace
		   content inside the scorecard shrinkable rather than forcing
		   horizontal overflow. */
		width: 100%;
		min-width: 0;
	}

	/* Severity dot — replaces the old "#N" step indicator. Renders an empty
	   cell when the block has no linked flagged issue, and a filled colored
	   circle when one or more issues point at the block. Severity is the
	   highest across all linked issues (see `blockIssueSeverity`). */
	.block-step-dot {
		grid-column: 2;
		justify-self: end;
		align-self: flex-start;
		width: 8px;
		height: 8px;
		margin-top: 18px;
		margin-right: 16px;
		border-radius: 50%;
		background: transparent;
	}
	.block-step-dot--info {
		background: var(--color-accent);
		box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-accent) 18%, transparent);
	}
	.block-step-dot--warning {
		background: var(--color-warning);
		box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-warning) 18%, transparent);
	}
	.block-step-dot--critical {
		background: var(--color-danger);
		box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-danger) 18%, transparent);
	}

	.block-wrapper {
		position: relative;
		max-width: 100%;
		animation: block-slide-up var(--duration-ceremonial-medium) var(--ease-standard) both;
		animation-delay: var(--enter-delay, 0ms);
		will-change: opacity, transform, filter;
		scroll-margin-top: 16px;
		border-radius: 8px;
		outline: 2px solid transparent;
		outline-offset: 2px;
		transition: outline-color var(--duration-snap) var(--ease-soft);
	}

	@keyframes block-pulse {
		0%   { outline-color: var(--color-accent); }
		70%  { outline-color: var(--color-accent); }
		100% { outline-color: transparent; }
	}

	.block-wrapper--highlighted {
		animation: block-pulse var(--duration-ceremonial-slow) var(--ease-soft) forwards;
	}

	/* Persistent severity-colored outline on the block linked to the currently
	   selected issue. Stays on until another issue is clicked, so the reader
	   can scroll around without losing the visual anchor. The brief pulse
	   above is animation-driven (transparent at end) while this is a static
	   outline-color override — they don't fight because nothing else sets
	   outline-color on .block-wrapper. */
	.block-wrapper--selected-info {
		outline-color: var(--color-accent);
	}
	.block-wrapper--selected-warning {
		outline-color: var(--color-warning);
	}
	.block-wrapper--selected-critical {
		outline-color: var(--color-danger);
	}

	.block-wrapper--no-anim {
		animation: none;
		opacity: 1;
		transform: none;
		filter: none;
	}

	/* ── Skeleton tool-call feed (mirrors recap-activity-stack) ──────────
	   Renders below the "Reviewing…" shimmer in the Phase-A/B skeleton.
	   `ToolActivityGroup` brings its own shimmer + odometer; when the
	   thoughts toggle is open, the same stack interleaves inline thought
	   markdown blocks chronologically between the groups. */
	.walkthrough-skeleton {
		display: flex;
		flex-direction: column;
		width: 100%;
	}

	.walkthrough-phase-trigger {
		display: flex;
		width: 100%;
		align-items: center;
		justify-content: space-between;
		gap: 0.75rem;
		padding: 0.125rem 0;
		text-align: left;
		background: transparent;
		border: 0;
		color: inherit;
		cursor: pointer;
		font: inherit;
	}

	.walkthrough-activity-stack {
		display: flex;
		flex-direction: column;
		margin-top: 0.375rem;
		padding-left: 0.75rem;
		border-left: 1px solid var(--color-border);
	}

	.walkthrough-activity-entry + .walkthrough-activity-entry {
		margin-top: 0.375rem;
	}

	.walkthrough-activity-entry[data-kind="thought"] + .walkthrough-activity-entry[data-kind="explorations"] {
		margin-top: 0.25rem;
	}

	.walkthrough-activity-entry[data-kind="explorations"] + .walkthrough-activity-entry[data-kind="thought"] {
		margin-top: 0.875rem;
	}

	.walkthrough-thought-empty {
		margin: 0.375rem 0 0;
		font-size: 0.8125rem;
		color: var(--color-text-muted);
	}

	.walkthrough-inline-thought {
		font-size: 0.875rem;
		line-height: 1.6;
		color: var(--color-text-muted);
		word-break: break-word;
	}

	/* Markdown styling comes from the app-wide themed @tailwindcss/typography
	   prose layer (see app.css); `.walkthrough-inline-thought` only sets the
	   quieter muted body tone. */

	/* ── Annotation rail ─────────────────────────────────────────────────
	   Sits top-aligned beside its block in the grid row. No sticky — CSS
	   sticky has no cross-sibling awareness, so two annotations in adjacent
	   rows will collide at top: 24px during the row-transition (while row N
	   is still partially on screen, row N+1's annotation has already started
	   sticking). Since code/diff blocks are capped at `min(70vh, 640px)` with
	   their own internal overflow, the outer page never scrolls past a single
	   block for long enough to need the annotation pinned — the whole row
	   (block + annotation) scrolls as a unit. */
	.block-annotation {
		align-self: start;
		padding: 4px 0;
		/* Match the block's entrance timing so rail text appears in sync
		   with its block. Paired with the --enter-delay inline style. */
		animation: block-slide-up var(--duration-ceremonial-medium) var(--ease-standard) both;
		animation-delay: var(--enter-delay, 0ms);
	}

	.block-annotation--no-anim {
		animation: none;
		opacity: 1;
		transform: none;
		filter: none;
	}

	.block-annotation-inner {
		/* Outlined card — matches the bordered treatment of the code/diff blocks
		   in the content column, so the rail reads as a balanced peer instead
		   of loose text next to a bordered panel. Uses the same border token
		   the code/diff blocks use (--color-border). */
		background: var(--color-bg-primary);
		border: 1px solid var(--color-border);
		border-radius: 8px;
		padding: 14px 16px;
		font-size: 14px;
		line-height: 1.6;
		color: var(--color-text-secondary);
		/* Allow long identifiers inside inline <code> (e.g. dotted API paths
		   like AuthService.isTokenRevoked(payload.jti)) to break anywhere so
		   they don't overflow the 380px card. `overflow-wrap: anywhere`
		   (rather than `break-word`) contributes to min-content sizing, which
		   keeps the card honest if a future narrower viewport lets grid col 5
		   shrink. */
		overflow-wrap: anywhere;
	}

	/* Markdown styling comes from the app-wide themed @tailwindcss/typography
	   prose layer (see app.css); `.block-annotation-inner` only owns the card box. */

	.loading-text {
		font-size: 13px;
		color: var(--color-text-muted);
	}

	.loading-subtext {
		font-size: 11px;
		color: var(--color-text-muted);
		opacity: 0.6;
		margin: 0;
	}

	.error-inline {
		font-size: 12px;
		color: var(--color-danger);
		margin-top: 8px;
	}

	/* ── Animations ──────────────────────────────────────────────────── */

	@keyframes fadeIn {
		from {
			opacity: 0;
			transform: translateY(4px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@keyframes content-enter {
		from {
			transform: translateY(6px);
			filter: blur(3px);
		}
		to {
			transform: translateY(0);
			filter: blur(0);
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.block-wrapper,
		.block-annotation,
		.issues-section,
		.walkthrough-content,
		.walkthrough-stepper-header,
		.dotmatrix-dot {
			animation-duration: 0.01ms !important;
			animation-delay: 0ms !important;
			transition: none !important;
		}
	}

	@keyframes block-slide-up {
		from {
			opacity: 0;
			transform: translateY(10px);
			filter: blur(4px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
			filter: blur(0);
		}
	}

	/* ── Clone-in-progress state ────────────────────────────────────── */

	.clone-progress-container {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 10px;
		width: 100%;
		max-width: 320px;
	}

	:global(.clone-progress-bar) {
		width: 100%;
	}

	/* ── Sentiment card ────────────────────────────────────────────────
	   Renders `walkthrough.sentiment` (Phase C markdown) as a distinct
	   accent-tinted card between the diff-step body and the 9-axis
	   scorecard. Styling tokens match the content column's markdown blocks
	   so inline code / lists / bold read consistently across the
	   walkthrough. :global() is required because renderMarkdown emits its
	   own DOM that isn't scoped to this component. */

	.sentiment-card {
		background: color-mix(in srgb, var(--color-accent) 5%, var(--color-bg-secondary));
		border: 1px solid color-mix(in srgb, var(--color-accent) 20%, transparent);
		border-radius: 10px;
		padding: 16px 20px;
	}

	.sentiment-card-header {
		margin-bottom: 10px;
	}

	.sentiment-card-title {
		font-size: 16px;
		font-weight: 600;
		color: var(--color-text-primary);
		margin: 0;
	}

	.sentiment-card-body {
		font-size: 14px;
		line-height: 1.65;
		color: var(--color-text-secondary);
	}

	/* Markdown styling comes from the app-wide themed @tailwindcss/typography
	   prose layer (see app.css); `.sentiment-card-body` only owns base text density. */

	/* ── Narrow-viewport fallback ────────────────────────────────────────
	   Below the 1336px geometric minimum (24 left + 48 + 820 + 40 + 380 +
	   24 right) the side-by-side grid physically can't fit. Stack the
	   annotation card directly below its block but keep the content column
	   pinned at col_3's leftmost position (col_1 floor 24 + col_2 48 = 72
	   from container left, 820 wide). At the breakpoint M=1335 this places
	   content at exactly 72–892 — the same span col_3 occupies at M=1336
	   in grid mode — so the right-pane animation crossing this threshold
	   no longer teleports the content. Expresses the "shift left until
	   it can't shift further, then drop annotations below" semantic:
	   left edge stays anchored at 72, annotations stack rather than
	   recentering the content.

	   Matches at `max-width: 1335px` (inclusive), so V=1336 is the first
	   width at which side-by-side activates. */
	@container (max-width: 1335px) {
		/* Pin content to col_3's leftmost x-position; cap width at col_3
		   max (820) plus right padding (32). Below 924px container width
		   the box shrinks with the container — left edge stays at 72. */
		.walkthrough-content {
			display: block;
			padding: 28px 32px 28px 72px;
			max-width: calc(72px + 820px + 32px);
			margin-inline: 0;
		}

		/* Children no longer need explicit column placement. */
		.walkthrough-content > .issues-section,
		.walkthrough-content > :global([data-slot="separator"]) {
			grid-column: auto;
		}

		/* Inner sections inherit .walkthrough-content's content area (820
		   wide, left-aligned at 72px from container). No re-centering or
		   extra horizontal padding — that would shift them inward of the
		   parent's content edges and break alignment with .blocks below. */
		.walkthrough-loading,
		.walkthrough-stepper-header {
			display: block;
			width: 100%;
			max-width: calc(72px + 820px + 32px);
			padding-left: 72px;
			padding-right: 32px;
			margin-inline: 0;
			box-sizing: border-box;
		}

		.walkthrough-loading {
			/* Restore the flex-column gap behavior we had before the grid was
			   introduced, so skeleton + status-bar + exploration-feed get the
			   20px vertical spacing back. */
			display: flex;
			flex-direction: column;
			gap: 20px;
			width: 100%;
		}

		.walkthrough-loading > :global(*),
		.walkthrough-stepper-header > * {
			grid-column: auto;
		}

		.blocks {
			display: block;
			grid-column: auto;
		}

		.block-group > .block-wrapper {
			grid-column: auto;
		}

		.block-group--sentiment-stack {
			grid-column: auto;
		}

		/* Annotation card stacks directly below its block. Sticky was already
		   removed at the wide layer; here we just give the stacked card a
		   small top margin so it reads as attached-to-but-distinct-from
		   its block. */
		.block-annotation {
			padding: 0;
			margin-top: 10px;
		}
	}
</style>
