import type { AgentAvailability, AiAgent, UserSettings } from "@revv/shared";
import { API_BASE_URL } from "$lib/api/base-url";
import { api } from "$lib/api/client";
import {
  getDefaultModel,
  getDefaultSuggestionsModel,
  type ModelOption,
} from "$lib/constants/models";
import { invalidateSuggestions } from "$lib/stores/suggestions.svelte";
import { authHeaders } from "$lib/utils/session-token";

let settings = $state<UserSettings | null>(null);
let _isLoading = $state(false);
let modelsByAgent = $state<Record<AiAgent, ModelOption[]>>({
  opencode: [],
  claude: [],
  codex: [],
});
let modelsLoadedByAgent = $state<Record<AiAgent, boolean>>({
  opencode: false,
  claude: false,
  codex: false,
});
let modelsInFlight: Partial<Record<AiAgent, Promise<ModelOption[]>>> = {};

export function getSettings(): UserSettings | null {
  return settings;
}

/**
 * GitHub host the app authenticates against. Returns `null` until the
 * settings file has been fetched at least once. The onboarding flow reads
 * this to decide whether to start at the Welcome step (no host yet) or
 * resume at Sign-In (host already picked).
 */
export function getGithubHost(): string | null {
  return settings?.githubHost ?? null;
}

/**
 * BYO OAuth/App client ID for a user-added GitHub Enterprise host. Empty for
 * github.com. The onboarding host step writes this alongside `githubHost`
 * when the user points Revv at their own GHE instance.
 */
export function getGithubClientId(): string {
  return settings?.githubClientId ?? "";
}

/**
 * Persist the host and its client ID together. Pass an empty `clientId` for
 * github.com so a previously-saved custom ID is cleared when switching back
 * to public GitHub.
 */
export async function setGithubConfig(host: string, clientId: string): Promise<void> {
  await updateSettings({ githubHost: host, githubClientId: clientId });
}

/**
 * Read the cached model list for a given agent (or the currently selected
 * agent when `agent` is omitted). Returns an empty array if models have not
 * been fetched yet — callers can use `areModelsLoaded` to disambiguate
 * "loading" from "genuinely empty".
 */
export function getAvailableModels(agent?: AiAgent): ModelOption[] {
  const a = agent ?? (settings?.aiAgent as AiAgent) ?? "opencode";
  return modelsByAgent[a] ?? [];
}

export function areModelsLoaded(agent: AiAgent): boolean {
  return modelsLoadedByAgent[agent] ?? false;
}

export async function fetchSettings(): Promise<void> {
  _isLoading = true;
  try {
    const { data } = await api.api.settings.get();
    if (data) settings = data as UserSettings;
  } catch {
    // handle silently
  } finally {
    _isLoading = false;
  }
}

/**
 * Shape accepted by `updateSettings`. Top-level fields are individually
 * optional. `recap` and `cache` are recursively partial so callers can
 * patch a single nested field (e.g. `{ cache: { enabled: true } }`)
 * without spreading the whole sub-object. The server deep-merges them
 * against the current values.
 */
export type SettingsUpdate = Partial<Omit<UserSettings, "id" | "recap" | "cache">> & {
  recap?: Partial<UserSettings["recap"]>;
  cache?: Partial<Omit<UserSettings["cache"], "signing">> & {
    signing?: Partial<UserSettings["cache"]["signing"]>;
  };
};

export async function updateSettings(partial: SettingsUpdate): Promise<void> {
  // Optimistic local merge — apply the partial immediately so concurrent calls
  // (e.g. model + context-window in the same popover session) don't clobber each
  // other when server responses arrive out of order. `recap` and `cache` are
  // deep-merged so a sub-field patch doesn't blow away the other sub-fields.
  if (settings) {
    const mergedRecap = partial.recap ? { ...settings.recap, ...partial.recap } : settings.recap;
    const mergedCache = partial.cache
      ? {
          ...settings.cache,
          ...partial.cache,
          signing: partial.cache.signing
            ? { ...settings.cache.signing, ...partial.cache.signing }
            : settings.cache.signing,
        }
      : settings.cache;
    settings = {
      ...settings,
      ...partial,
      recap: mergedRecap,
      cache: mergedCache,
    } as UserSettings;
  }
  // Drop the cached right-panel suggestions whenever the model or agent
  // changes — the previously-fetched prompts were generated by a
  // different model and the user expects the new selection to take effect
  // on the next PR open without a refresh. Server keeps its own cache
  // keyed on `(prId, headSha, model)` so the client miss simply lands on
  // a different cache row.
  if ("aiSuggestionsModel" in partial || "aiAgent" in partial) {
    invalidateSuggestions();
  }
  try {
    await api.api.settings.put(partial as Record<string, unknown>);
    // Intentionally ignore the response body: merging a full settings object
    // here would reintroduce the race described above.
  } catch {
    // handle silently
  }
}

export function reset(): void {
  settings = null;
  _isLoading = false;
  modelsByAgent = { opencode: [], claude: [], codex: [] };
  modelsLoadedByAgent = { opencode: false, claude: false, codex: false };
  modelsInFlight = {};
  agentAvailability = null;
}

/**
 * Fetch the model list for a specific agent and cache it. Concurrent calls for
 * the same agent de-dupe onto a single in-flight request so rapid agent toggles
 * don't thrash the server.
 */
export async function fetchModels(agent: AiAgent): Promise<ModelOption[]> {
  const existing = modelsInFlight[agent];
  if (existing) return existing;

  const url = `${API_BASE_URL}/api/settings/models?agent=${encodeURIComponent(agent)}`;
  const promise = (async () => {
    try {
      const res = await fetch(url, { headers: authHeaders() });
      if (!res.ok) return modelsByAgent[agent] ?? [];
      const data = (await res.json()) as { models: ModelOption[] };
      const list = data.models ?? [];
      modelsByAgent = { ...modelsByAgent, [agent]: list };
      modelsLoadedByAgent = { ...modelsLoadedByAgent, [agent]: true };
      return list;
    } catch {
      return modelsByAgent[agent] ?? [];
    } finally {
      delete modelsInFlight[agent];
    }
  })();

  modelsInFlight[agent] = promise;
  return promise;
}

/**
 * Prefetch models for every supported agent in parallel. Call this once at
 * app start so agent/model dropdowns render instantly without round-trips.
 */
export async function fetchAllModels(): Promise<void> {
  await Promise.all([fetchModels("opencode"), fetchModels("claude"), fetchModels("codex")]);
}

/**
 * Build the three-field settings partial used when the agent flips:
 * `aiAgent` + `aiModel` (re-picked against the new agent's catalog) +
 * `aiSuggestionsModel` (low-cost default for the new agent).
 *
 * Centralises the cascade logic that lived in AgentSelector and
 * SettingsModal so the onboarding agent step doesn't have to copy it a
 * third time. Side-effect free — callers pass the result to
 * `updateSettings()`.
 */
export function cascadeAgentChange(agent: AiAgent): {
  aiAgent: AiAgent;
  aiModel: string;
  aiSuggestionsModel: string;
} {
  const cached = getAvailableModels(agent);
  const fallback = getDefaultModel(agent);
  const picked =
    cached.length === 0
      ? fallback
      : // biome-ignore lint/style/noNonNullAssertion: length > 0 guarantees [0] exists
        (cached.find((m) => m.value === fallback)?.value ?? cached[0]!.value);
  return {
    aiAgent: agent,
    aiModel: picked,
    aiSuggestionsModel: getDefaultSuggestionsModel(agent),
  };
}

// ── Agent availability ──────────────────────────────────────────────────────
// Cached snapshot of which CLI agents are installed locally. Used by the
// onboarding agent step to decide between the picker and the install
// prompt. Stays null until `fetchAgentAvailability()` runs, since first
// render has nothing useful to show.

let agentAvailability = $state<AgentAvailability | null>(null);

export function getAgentAvailability(): AgentAvailability | null {
  return agentAvailability;
}

export async function fetchAgentAvailability(): Promise<AgentAvailability | null> {
  try {
    const res = await fetch(`${API_BASE_URL}/api/onboarding/agent-availability`, {
      headers: authHeaders(),
    });
    if (!res.ok) return agentAvailability;
    const data = (await res.json()) as AgentAvailability;
    agentAvailability = data;
    return data;
  } catch {
    return agentAvailability;
  }
}
