// ── Walkthrough store ───────────────────────────────────────────────────────
//
// Single module covering reactive state, the event reducer, the
// global-SSE entry point, and the few REST helpers needed for
// regenerate/resume/hydrate/abort. Replaces the previous three-layer
// split (state + transport + ui-state projection) — once walkthrough
// events moved to the global SSE bus the per-PR streaming machinery
// (controllers, stream cap, snapshot replay, reconciliation poll) was
// no longer needed and the layering carried more weight than it earned.
//
// Lifecycle:
//   1. `events.svelte.ts` opens the global SSE and dispatches every
//      `walkthrough:event` envelope through `onWalkthroughEvent`.
//   2. Component mounts call `prepareEntry` (sync seed) + `hydrateFromCache`
//      (REST snapshot). If the server is still generating, subsequent
//      content events arrive over the same SSE without any per-PR
//      subscription.
//   3. Regenerate / resume hit a REST endpoint; the server fires
//      `lifecycle:*` events that the reducer applies.

import type {
  Activity,
  ActivityResult,
  CloneStatus,
  RiskLevel,
  WalkthroughBlock,
  WalkthroughIssue,
  WalkthroughLifecyclePhase,
  WalkthroughMode,
  WalkthroughPipelinePhase,
  WalkthroughRating,
  WalkthroughReviewRoundsResponse,
  WalkthroughSemanticStep,
  WalkthroughStreamEvent,
  WalkthroughTokenUsage,
} from "@revv/shared";
import { SvelteMap } from "svelte/reactivity";
import { toast } from "svelte-sonner";
import { API_BASE_URL } from "$lib/api/base-url";
import { api } from "$lib/api/client";
import { getReviewModeForPr, updateRepoCloneStatus } from "$lib/stores/prs.svelte";
import { authHeaders } from "$lib/utils/session-token";
import { wtTrace } from "$lib/utils/wt-trace";

// ── Entry shape ─────────────────────────────────────────────────────────────

/**
 * Chronologically ordered live-feed entry mixing model reasoning ("thought")
 * with built-in exploration tool calls ("exploration"). Populated only during
 * streaming so the client can render the "Reviewing…" feed with thoughts and
 * tool calls interleaved in arrival order. Not persisted — rebuilt fresh on
 * every stream.
 */
export type WalkthroughTimelineEntry =
  | { kind: "thought"; id: string; text: string }
  | { kind: "exploration"; id: string; activity: Activity };

export interface WalkthroughEntry {
  mode: WalkthroughMode;
  semanticSteps: WalkthroughSemanticStep[];
  blocks: WalkthroughBlock[];
  summary: string | null;
  riskLevel: RiskLevel | null;
  sentiment: string | null;
  lastCompletedPhase: WalkthroughPipelinePhase;
  isStreaming: boolean;
  streamError: string | null;
  walkthroughId: string | null;
  doneReceived: boolean;
  superseded: boolean;
  historical: boolean;
  explorationSteps: Activity[];
  /**
   * Captured tool outputs keyed by provider `callId`, merged into each
   * exploration pill so its peek can render stdout / results. Ephemeral —
   * populated from `exploration-result` events during live generation only.
   */
  explorationResults: Record<string, ActivityResult>;
  /**
   * Late-arriving tool inputs keyed by provider `callId`, merged into each
   * exploration pill so its filename/command + file peek resolve when the agent
   * only supplies them after the tool-call. Ephemeral (live generation only).
   */
  explorationInputs: Record<string, unknown>;
  /**
   * Chronological mix of thoughts and exploration tool calls for the live
   * "Reviewing…" feed. See `WalkthroughTimelineEntry`. Ephemeral. The thoughts
   * toggle UI renders from this directly — there is no separate concatenated
   * thoughts string.
   */
  timeline: WalkthroughTimelineEntry[];
  issues: WalkthroughIssue[];
  ratings: WalkthroughRating[];
  phase: WalkthroughLifecyclePhase;
  phaseMessage: string;
  streamStartedAt: number | null;
  liveGeneration: boolean;
  cloneInProgress: boolean;
  cloneRepoId: string | null;
  tokenUsage: WalkthroughTokenUsage;
  source: "local" | "remote";
  /**
   * Attribution shown in the header ("Generated by @alice"). Available
   * regardless of `source` so the badge renders on both local and cache-
   * hit paths. `null` when the row predates the attribution migration.
   */
  generatedBy: {
    githubUserId: number | null;
    githubLogin: string | null;
    displayName: string | null;
    avatarContent: string | null;
  } | null;
  /**
   * Snapshot of the AI provider config in effect when this walkthrough
   * was originally generated (locally or by a teammate). Shown as
   * "claude-opus-4-8 • thinking: high" in the header detail line.
   */
  providerConfig: {
    provider: string;
    model: string;
    thinkingEffort: string | null;
    contextWindow: string | null;
    maxTurns: number;
  } | null;
}

export const ZERO_TOKEN_USAGE: WalkthroughTokenUsage = Object.freeze({
  inputTokens: 0,
  outputTokens: 0,
  cacheReadInputTokens: 0,
  cacheCreationInputTokens: 0,
  contextTokens: 0,
});

export function coerceTokenUsage(raw: unknown): WalkthroughTokenUsage {
  if (raw === null || typeof raw !== "object") return { ...ZERO_TOKEN_USAGE };
  const r = raw as Record<string, unknown>;
  const num = (v: unknown): number => (typeof v === "number" && Number.isFinite(v) ? v : 0);
  const inputTokens = num(r.inputTokens);
  const outputTokens = num(r.outputTokens);
  const cacheReadInputTokens = num(r.cacheReadInputTokens);
  const cacheCreationInputTokens = num(r.cacheCreationInputTokens);
  const contextWindowTokens = num(r.contextWindowTokens);
  // Walkthroughs generated before context occupancy was tracked carry no
  // `contextTokens`. Fall back to the throughput sum (the gauge's old formula)
  // so historical PRs render a populated gauge instead of an empty 0% ring;
  // freshly generated rows always carry a real point-in-time value.
  const contextTokens =
    typeof r.contextTokens === "number" && Number.isFinite(r.contextTokens)
      ? r.contextTokens
      : inputTokens + outputTokens + cacheReadInputTokens + cacheCreationInputTokens;
  return {
    inputTokens,
    outputTokens,
    cacheReadInputTokens,
    cacheCreationInputTokens,
    contextTokens,
    ...(contextWindowTokens > 0 ? { contextWindowTokens } : {}),
  };
}

export function freshEntry(): WalkthroughEntry {
  return {
    mode: "reviewer",
    semanticSteps: [],
    blocks: [],
    summary: null,
    riskLevel: null,
    sentiment: null,
    lastCompletedPhase: "none",
    isStreaming: true,
    streamError: null,
    walkthroughId: null,
    doneReceived: false,
    superseded: false,
    historical: false,
    explorationSteps: [],
    explorationResults: {},
    explorationInputs: {},
    timeline: [],
    issues: [],
    ratings: [],
    phase: "connecting",
    phaseMessage: "Connecting...",
    streamStartedAt: Date.now(),
    liveGeneration: false,
    cloneInProgress: false,
    cloneRepoId: null,
    tokenUsage: { ...ZERO_TOKEN_USAGE },
    source: "local",
    generatedBy: null,
    providerConfig: null,
  };
}

// ── Reactive state ──────────────────────────────────────────────────────────

export const store = $state({
  // SvelteMap (not plain `Map`): plain `Map` mutations don't trigger Svelte
  // reactivity, and the previous `entries = new Map(entries)` workaround
  // was unreliable across module boundaries.
  entries: new SvelteMap<string, WalkthroughEntry>(),
  activePrId: null as string | null,
  /**
   * Per-walkthroughId monotonic seq cursor. Set by `hydrateFromCache`
   * (from the REST snapshot's `seqAt`) and advanced by every applied
   * `walkthrough:event` envelope. The reducer drops envelopes with
   * `seq <= lastSeenSeq[walkthroughId]` defensively — they're either a
   * re-delivery during EventSource reconnect or content already covered
   * by a more recent REST snapshot.
   */
  lastSeenSeq: new SvelteMap<string, number>(),
  /**
   * Null means "follow the current/latest walkthrough for this PR".
   * A walkthrough id means the user intentionally selected a historical
   * report, so unrelated live events must not mutate the displayed content.
   */
  selectedReportIds: new SvelteMap<string, string | null>(),
});

const PHASE_RANK: Record<WalkthroughPipelinePhase, number> = {
  none: 0,
  A: 1,
  B: 2,
  C: 3,
  D: 4,
};

// `_active` is the single reactive derivation that resolves the current PR's
// walkthrough entry. Do NOT "simplify" this back to a plain function — Svelte
// 5's dependency tracking through a plain function → Map.get() across module
// boundaries silently kept a stale cached result, manifesting as floating
// action buttons stuck on "Stop" until a tab switch forced the $derived to
// re-evaluate.
const _active: WalkthroughEntry | undefined = $derived.by(() => {
  if (!store.activePrId) return undefined;
  return store.entries.get(store.activePrId);
});

// ── Mutation helpers ────────────────────────────────────────────────────────

export function setEntry(prId: string, entry: WalkthroughEntry): void {
  store.entries.set(prId, entry);
}

export function deleteEntry(prId: string): void {
  store.entries.delete(prId);
  lastEventAtByPr.delete(prId);
}

export function getSelectedReportId(prId: string): string | null {
  return store.selectedReportIds.get(prId) ?? null;
}

export function getDisplayedWalkthroughId(prId?: string): string | null {
  const id = prId ?? store.activePrId;
  if (!id) return null;
  return store.entries.get(id)?.walkthroughId ?? null;
}

// ── Stream-liveness tracking ──────────────────────────────────────────────
//
// Non-reactive wall-clock timestamp of the last `walkthrough:event` applied
// for each PR. Read imperatively by the per-walkthrough stall watchdog
// (GuidedWalkthrough) — NOT reactive state, so stamping it on every streamed
// event doesn't churn Svelte's dependency graph. Lets the client detect a
// stream that went silent without a terminal `lifecycle:complete` /
// `lifecycle:error` (missed SSE envelopes for a fast-failing job, a brief
// broadcast/registration race, etc.) and reconcile against the authoritative
// DB via REST — the same SSE-is-best-effort recovery the clone poller does
// (doctrine invariant #8).
const lastEventAtByPr = new Map<string, number>();

/**
 * Wall-clock ms of the last streamed walkthrough event applied for `prId`,
 * or `null` if none has arrived this session. Drives the stall watchdog.
 */
export function getLastWalkthroughEventAt(prId: string): number | null {
  return lastEventAtByPr.get(prId) ?? null;
}

export function updateEntry(prId: string, updater: (e: WalkthroughEntry) => void): void {
  const entry = store.entries.get(prId);
  if (!entry) {
    wtTrace("store", `updateEntry-noop prId=${prId} reason=no-entry`);
    return;
  }
  const next = { ...entry };
  updater(next);
  store.entries.set(prId, next);
}

// ── Getters ─────────────────────────────────────────────────────────────────

export function getBlocks(): WalkthroughBlock[] {
  return _active?.blocks ?? [];
}
export function getSemanticSteps(): WalkthroughSemanticStep[] {
  return _active?.semanticSteps ?? [];
}
export function getSummary(): string | null {
  return _active?.summary ?? null;
}
export function getRiskLevel(): RiskLevel | null {
  return _active?.riskLevel ?? null;
}
export function getIsStreaming(): boolean {
  return _active?.isStreaming ?? false;
}
export function getStreamError(): string | null {
  return _active?.streamError ?? null;
}
export function getExplorationSteps(): Activity[] {
  return _active?.explorationSteps ?? [];
}
export function getExplorationResults(): Record<string, ActivityResult> {
  return _active?.explorationResults ?? {};
}
export function getExplorationInputs(): Record<string, unknown> {
  return _active?.explorationInputs ?? {};
}
export function getTimeline(): WalkthroughTimelineEntry[] {
  return _active?.timeline ?? [];
}
export function getIssues(): WalkthroughIssue[] {
  return _active?.issues ?? [];
}
export function getIssuesForFile(filePath: string): WalkthroughIssue[] {
  const issues = _active?.issues ?? [];
  return issues.filter((i) => i.filePath === filePath);
}
export function getRatings(): WalkthroughRating[] {
  return _active?.ratings ?? [];
}
export function getPhase(): WalkthroughLifecyclePhase {
  return _active?.phase ?? "connecting";
}
export function getStreamStartedAt(): number | null {
  return _active?.streamStartedAt ?? null;
}
export function getIsLiveGeneration(): boolean {
  return _active?.liveGeneration ?? false;
}
export function getCloneInProgress(): boolean {
  return _active?.cloneInProgress ?? false;
}
export function getCloneRepoId(): string | null {
  return _active?.cloneRepoId ?? null;
}
export function getSentiment(): string | null {
  return _active?.sentiment ?? null;
}
export function getLastCompletedPhase(): WalkthroughPipelinePhase {
  return _active?.lastCompletedPhase ?? "none";
}
export function getIsSuperseded(): boolean {
  return _active?.superseded ?? false;
}

export function markWalkthroughStale(prId: string): void {
  updateEntry(prId, (entry) => {
    if (!entry.doneReceived || entry.superseded) return;
    entry.superseded = true;
    entry.isStreaming = false;
    entry.liveGeneration = false;
    entry.streamError = null;
  });
}
export function getSource(): "local" | "remote" {
  return _active?.source ?? "local";
}
export function getGeneratedBy(): WalkthroughEntry["generatedBy"] {
  return _active?.generatedBy ?? null;
}
export function getProviderConfig(): WalkthroughEntry["providerConfig"] {
  return _active?.providerConfig ?? null;
}
export function getTokenUsage(prId?: string): WalkthroughTokenUsage {
  const id = prId ?? store.activePrId;
  if (!id) return ZERO_TOKEN_USAGE;
  return store.entries.get(id)?.tokenUsage ?? ZERO_TOKEN_USAGE;
}

// ── State queries ───────────────────────────────────────────────────────────

export function getPrWalkthroughStatus(prId: string): "idle" | "generating" | "complete" | "error" {
  const entry = store.entries.get(prId);
  if (!entry) return "idle";
  if (entry.isStreaming) return "generating";
  if (entry.streamError) return "error";
  if (entry.summary) return "complete";
  return "idle";
}

// ── UI state projection ─────────────────────────────────────────────────────

export type WalkthroughUiState =
  | { kind: "absent" }
  | { kind: "idle" }
  | { kind: "cloning"; repoId: string }
  | { kind: "streaming"; phase: WalkthroughLifecyclePhase }
  | { kind: "resumable"; lastPhase: WalkthroughPipelinePhase }
  | { kind: "complete" }
  | { kind: "complete-stale" }
  | { kind: "error-empty"; message: string }
  | { kind: "error-partial"; message: string; lastPhase: WalkthroughPipelinePhase };

const _uiState: WalkthroughUiState = $derived.by((): WalkthroughUiState => {
  const e = _active;
  if (!e) return { kind: "absent" };
  if (e.cloneInProgress && e.cloneRepoId) {
    return { kind: "cloning", repoId: e.cloneRepoId };
  }
  if (e.isStreaming) return { kind: "streaming", phase: e.phase };

  const hasPartial = e.summary !== null || e.blocks.length > 0;

  if (e.superseded) {
    return { kind: "complete-stale" };
  }

  if (e.streamError) {
    return hasPartial
      ? { kind: "error-partial", message: e.streamError, lastPhase: e.lastCompletedPhase }
      : { kind: "error-empty", message: e.streamError };
  }
  if (e.historical) {
    return e.superseded ? { kind: "complete-stale" } : { kind: "complete" };
  }
  if (e.doneReceived && e.lastCompletedPhase === "D") {
    return e.superseded ? { kind: "complete-stale" } : { kind: "complete" };
  }
  if (hasPartial) {
    return { kind: "resumable", lastPhase: e.lastCompletedPhase };
  }
  return { kind: "idle" };
});

export function getWalkthroughUiState(): WalkthroughUiState {
  return _uiState;
}

// ── Pending action tracker ──────────────────────────────────────────────────
//
// Drives the `disabled` state on Regenerate / Resume floating buttons so a
// double-click can't fire two concurrent destructive actions during the async
// POST → reset-entry → SSE-event dance.

export type PendingAction = "regenerate" | "resume" | "start";

const pendingActions = $state({
  map: new SvelteMap<string, PendingAction>(),
});

type ReviewRoundsEntry =
  | { status: "idle" | "loading" }
  | { status: "error"; error: string }
  | { status: "ready"; data: WalkthroughReviewRoundsResponse };

const reviewRounds = $state({
  entries: new SvelteMap<string, ReviewRoundsEntry>(),
});

const pendingReviewRoundLoads = new Map<string, Promise<WalkthroughReviewRoundsResponse | null>>();

function reviewRoundsKey(prId: string, mode: WalkthroughMode): string {
  return `${prId}:${mode}`;
}

export function getReviewRounds(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
): WalkthroughReviewRoundsResponse | null {
  const entry = reviewRounds.entries.get(reviewRoundsKey(prId, mode));
  return entry?.status === "ready" ? entry.data : null;
}

export function getHasUnreviewedCommits(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
): boolean {
  return getReviewRounds(prId, mode)?.hasNewCommits ?? false;
}

export async function loadReviewRounds(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
): Promise<WalkthroughReviewRoundsResponse | null> {
  const key = reviewRoundsKey(prId, mode);
  const inflight = pendingReviewRoundLoads.get(key);
  if (inflight) return inflight;

  const promise = (async () => {
    reviewRounds.entries.set(key, { status: "loading" });
    try {
      const res = await fetch(
        `${API_BASE_URL}/api/reviews/${prId}/walkthrough/rounds?mode=${mode}`,
        {
          headers: authHeaders(),
          credentials: "include",
        },
      );
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as WalkthroughReviewRoundsResponse;
      reviewRounds.entries.set(key, { status: "ready", data });
      return data;
    } catch (e) {
      reviewRounds.entries.set(key, {
        status: "error",
        error: e instanceof Error ? e.message : String(e),
      });
      return null;
    } finally {
      pendingReviewRoundLoads.delete(key);
    }
  })();

  pendingReviewRoundLoads.set(key, promise);
  return promise;
}

export function refreshReviewRoundsForPrs(prIds: readonly string[]): void {
  for (const prId of prIds) {
    const mode = getSelectedMode(prId);
    if (
      reviewRounds.entries.has(reviewRoundsKey(prId, mode)) ||
      store.entries.has(prId) ||
      store.activePrId === prId
    ) {
      void loadReviewRounds(prId, mode);
    }
  }
}

export async function selectWalkthroughReport(
  prId: string,
  walkthroughId: string | null,
  mode: WalkthroughMode = getSelectedMode(prId),
): Promise<void> {
  store.selectedReportIds.set(prId, walkthroughId);
  store.activePrId = prId;
  clearAnimationTrackers(prId);
  const ok = await hydrateFromCache(prId, {
    mode,
    reportId: walkthroughId,
    replace: true,
  });
  if (!ok) {
    updateEntry(prId, (entry) => {
      entry.isStreaming = false;
      entry.streamError =
        walkthroughId === null
          ? "Failed to load the latest walkthrough report."
          : "Failed to load the selected walkthrough report.";
    });
  }
}

function setPending(prId: string, action: PendingAction): void {
  pendingActions.map.set(prId, action);
}

function clearPending(prId: string): void {
  if (!pendingActions.map.has(prId)) return;
  pendingActions.map.delete(prId);
}

export function getPendingAction(prId: string): PendingAction | null {
  return pendingActions.map.get(prId) ?? null;
}

// ── Event reducer ───────────────────────────────────────────────────────────

export function applyEvents(prId: string, events: WalkthroughStreamEvent[]): void {
  if (events.length > 0) {
    const types = events.map((e) => e.type).join(",");
    wtTrace("apply", `applyEvents prId=${prId} count=${events.length} types=[${types}]`);
  }
  updateEntry(prId, (entry) => {
    let newBlocks: WalkthroughBlock[] | null = null;

    for (const event of events) {
      switch (event.type) {
        case "summary":
          entry.summary = event.data.summary;
          entry.riskLevel = event.data.riskLevel;
          break;
        case "sentiment":
          entry.sentiment = event.data.sentiment;
          break;
        case "semantic-step": {
          const idx = entry.semanticSteps.findIndex(
            (s) => s.semanticStepIndex === event.data.semanticStepIndex,
          );
          if (idx >= 0) {
            entry.semanticSteps = entry.semanticSteps.map((s, i) => (i === idx ? event.data : s));
          } else {
            entry.semanticSteps = [...entry.semanticSteps, event.data].sort(
              (a, b) => a.semanticStepIndex - b.semanticStepIndex,
            );
          }
          break;
        }
        case "block": {
          if (!newBlocks) newBlocks = [...entry.blocks];
          const bi = newBlocks.findIndex((b) => b.id === event.data.id);
          if (bi >= 0) {
            newBlocks[bi] = event.data;
          } else {
            newBlocks.push(event.data);
          }
          break;
        }
        case "done":
          entry.walkthroughId = event.data.walkthroughId;
          entry.doneReceived = true;
          entry.isStreaming = false;
          entry.tokenUsage = coerceTokenUsage(event.data.tokenUsage);
          if (entry.summary !== null && entry.blocks.length > 0 && entry.ratings.length === 9) {
            entry.lastCompletedPhase = "D";
          }
          break;
        case "usage":
          entry.tokenUsage = coerceTokenUsage(event.data.tokenUsage);
          break;
        case "exploration": {
          entry.explorationSteps = [...entry.explorationSteps, event.data];
          entry.timeline = [
            ...entry.timeline,
            {
              kind: "exploration",
              id: `exp-${entry.timeline.length}`,
              activity: event.data,
            },
          ];
          break;
        }
        case "exploration-result": {
          entry.explorationResults = {
            ...entry.explorationResults,
            [event.data.callId]: event.data,
          };
          break;
        }
        case "exploration-input": {
          entry.explorationInputs = {
            ...entry.explorationInputs,
            [event.data.callId]: event.data.payload,
          };
          break;
        }
        case "thought": {
          // Append to last thought-run instead of pushing a new entry per
          // delta — the model emits hundreds of tiny deltas per burst, and
          // we only want a new timeline entry when a tool call (or some
          // other non-thought event) has broken the run.
          const last = entry.timeline.at(-1);
          if (last && last.kind === "thought") {
            entry.timeline = [
              ...entry.timeline.slice(0, -1),
              { ...last, text: last.text + event.data.text },
            ];
          } else {
            entry.timeline = [
              ...entry.timeline,
              {
                kind: "thought",
                id: `thought-${entry.timeline.length}`,
                text: event.data.text,
              },
            ];
          }
          break;
        }
        case "issue": {
          const ii = entry.issues.findIndex((i) => i.id === event.data.id);
          if (ii >= 0) {
            entry.issues = entry.issues.map((i, x) => (x === ii ? event.data : i));
          } else {
            entry.issues = [...entry.issues, event.data];
          }
          break;
        }
        case "rating": {
          const idx = entry.ratings.findIndex((r) => r.axis === event.data.axis);
          if (idx >= 0) {
            entry.ratings = entry.ratings.map((r, i) => (i === idx ? event.data : r));
          } else {
            entry.ratings = [...entry.ratings, event.data];
          }
          break;
        }
        case "phase":
          entry.phase = event.data.phase;
          entry.phaseMessage = event.data.message;
          if (event.data.phase !== "connecting") {
            entry.liveGeneration = true;
          }
          break;
        case "phase:advanced":
          entry.lastCompletedPhase = event.data.lastCompletedPhase;
          entry.liveGeneration = true;
          break;
        case "error":
          if (event.data.code === "CloneInProgress" && event.data.repoId != null) {
            entry.cloneInProgress = true;
            entry.cloneRepoId = event.data.repoId;
            entry.isStreaming = false;
          } else if (event.data.code === "CloneInProgress") {
            entry.cloneInProgress = false;
            entry.cloneRepoId = null;
            entry.isStreaming = false;
            entry.streamError =
              "Walkthrough could not start: the repository is cloning, but the server did not report which one. Retry to try again.";
          } else {
            entry.streamError = event.data.message;
            entry.isStreaming = false;
          }
          break;
        case "in-progress":
          entry.walkthroughId = event.data.walkthroughId;
          entry.phase = "writing";
          entry.phaseMessage = "Generating walkthrough...";
          entry.liveGeneration = true;
          break;
        case "thinking":
          break;
        case "block:deleted":
          if (!newBlocks) newBlocks = [...entry.blocks];
          newBlocks = newBlocks.filter((b) => b.id !== event.data.id);
          break;
        case "rating:deleted":
          entry.ratings = entry.ratings.filter((r) => r.axis !== event.data.axis);
          break;
        case "issue:deleted":
          entry.issues = entry.issues.filter((i) => i.id !== event.data.id);
          break;
        case "semantic-step:deleted": {
          const idx = event.data.semanticStepIndex;
          entry.semanticSteps = entry.semanticSteps.filter((s) => s.semanticStepIndex !== idx);
          if (!newBlocks) newBlocks = [...entry.blocks];
          newBlocks = newBlocks.filter((b) => b.semanticStepIndex !== idx);
          break;
        }
        // ── Lifecycle events (global SSE bus). Flip
        //    streaming/completion/error/superseded state without touching
        //    content. Each one was previously a standalone lifecycle envelope.
        case "lifecycle:started":
          entry.walkthroughId = event.data.walkthroughId;
          entry.mode = event.data.mode ?? entry.mode;
          entry.isStreaming = true;
          entry.doneReceived = false;
          entry.streamError = null;
          entry.superseded = false;
          entry.historical = false;
          entry.liveGeneration = true;
          entry.phase = "connecting";
          entry.phaseMessage = "Starting walkthrough…";
          if (entry.streamStartedAt === null) entry.streamStartedAt = Date.now();
          if (event.data.status === "cloning" && event.data.repoId) {
            entry.cloneInProgress = true;
            entry.cloneRepoId = event.data.repoId;
            entry.isStreaming = false;
          } else {
            entry.cloneInProgress = false;
            entry.cloneRepoId = null;
          }
          break;
        case "lifecycle:complete":
          entry.walkthroughId = event.data.walkthroughId;
          entry.doneReceived = true;
          entry.isStreaming = false;
          entry.tokenUsage = coerceTokenUsage(event.data.tokenUsage);
          if (entry.summary !== null && entry.blocks.length > 0 && entry.ratings.length === 9) {
            entry.lastCompletedPhase = "D";
          }
          break;
        case "lifecycle:error":
          if (event.data.code === "CloneInProgress" && event.data.repoId) {
            entry.cloneInProgress = true;
            entry.cloneRepoId = event.data.repoId;
            entry.isStreaming = false;
          } else if (event.data.code === "Cancelled") {
            // User-initiated stop — not a failure. Suppress the error
            // notification so the UI falls through to the "resumable" / "idle"
            // state based on whether partial content exists.
            entry.streamError = null;
            entry.isStreaming = false;
          } else {
            entry.streamError = event.data.message;
            entry.isStreaming = false;
          }
          break;
        case "lifecycle:cache-hit":
          entry.source = "remote";
          entry.walkthroughId = event.data.walkthroughId;
          break;
        case "lifecycle:edited":
          // No state change — the inner block/issue/etc. event lands in the
          // same stream as a separate envelope (with its own seq). This
          // marker is purely diagnostic / future-proofing.
          break;
        case "lifecycle:superseded":
          entry.superseded = true;
          entry.isStreaming = false;
          break;
      }
    }

    if (newBlocks) {
      newBlocks.sort((a, b) => a.order - b.order);
      entry.blocks = newBlocks;
    }
  });
}

// ── Global SSE event entry point ────────────────────────────────────────────

export function onWalkthroughEvent(
  prId: string,
  walkthroughId: string,
  seq: number,
  event: WalkthroughStreamEvent,
): void {
  const selectedReportId = store.selectedReportIds.get(prId) ?? null;
  if (selectedReportId !== null && selectedReportId !== walkthroughId) {
    if (event.type === "lifecycle:complete") {
      void loadReviewRounds(prId, getSelectedMode(prId));
      if (store.activePrId !== prId) {
        toast.success("Walkthrough ready", {
          description: "Switch to that PR to review.",
        });
      }
    }
    return;
  }

  const cursor = store.lastSeenSeq.get(walkthroughId) ?? -1;
  if (seq <= cursor) {
    wtTrace(
      "apply",
      `onWalkthroughEvent-drop wt=${walkthroughId} seq=${seq} cursor=${cursor} type=${event.type}`,
    );
    return;
  }

  // `lifecycle:started` may be the first signal we get for a PR the user
  // isn't currently viewing (background generation). Seed an entry so the
  // sidebar spinner has something to read.
  if (event.type === "lifecycle:started" && !store.entries.has(prId)) {
    const stub = freshEntry();
    stub.mode = event.data.mode ?? getSelectedMode(prId);
    stub.walkthroughId = walkthroughId;
    stub.isStreaming = event.data.status !== "cloning";
    stub.liveGeneration = true;
    stub.phase = "connecting";
    stub.phaseMessage = "Starting walkthrough…";
    if (event.data.status === "cloning" && event.data.repoId) {
      stub.cloneInProgress = true;
      stub.cloneRepoId = event.data.repoId;
      stub.isStreaming = false;
    }
    setEntry(prId, stub);
  }

  applyEvents(prId, [event]);
  store.lastSeenSeq.set(walkthroughId, seq);
  // Stamp stream liveness so the stall watchdog measures from the last
  // genuinely-delivered event rather than from stream start.
  lastEventAtByPr.set(prId, Date.now());

  if (event.type === "lifecycle:complete") {
    const entry = store.entries.get(prId);
    if (
      entry &&
      (entry.summary === null || entry.blocks.length === 0 || entry.ratings.length < 9)
    ) {
      void hydrateFromCache(prId, { activate: store.activePrId === prId });
    }
    void loadReviewRounds(prId, getSelectedMode(prId));
  }

  // Background-completion toast: only if the completion event landed on a
  // PR the user isn't actively viewing.
  if (event.type === "lifecycle:complete" && store.activePrId !== prId) {
    toast.success("Walkthrough ready", {
      description: "Switch to that PR to review.",
    });
  }
}

/**
 * On SSE (re)connect: seed entries for any in-flight walkthroughs owned
 * by the user's account. Each cursor returned by `/active` is only safe
 * after the matching REST snapshot has been merged into the store; otherwise
 * the UI would drop already-written events without ever rendering the content
 * they represent.
 */
export async function hydrateActiveWalkthroughs(): Promise<void> {
  try {
    const res = await fetch(`${API_BASE_URL}/api/walkthroughs/active`, {
      headers: authHeaders(),
      credentials: "include",
    });
    if (!res.ok) return;
    const body = (await res.json()) as {
      walkthroughs: Array<{
        prId: string;
        walkthroughId: string;
        prHeadSha: string;
        mode?: WalkthroughMode;
        seqAt: number;
      }>;
    };
    for (const row of body.walkthroughs) {
      const mode = row.mode ?? getSelectedMode(row.prId);
      const selectedReportId = store.selectedReportIds.get(row.prId) ?? null;
      if (selectedReportId !== null && selectedReportId !== row.walkthroughId) {
        continue;
      }

      const existing = store.entries.get(row.prId);
      if (!existing) {
        const stub = freshEntry();
        stub.walkthroughId = row.walkthroughId;
        stub.mode = mode;
        stub.isStreaming = true;
        stub.liveGeneration = true;
        stub.phase = "writing";
        stub.phaseMessage = "Generating walkthrough…";
        setEntry(row.prId, stub);
      }
      const hydrated = await hydrateFromCache(row.prId, {
        activate: store.activePrId === row.prId,
        mode,
      });
      if (hydrated) {
        const existingSeq = store.lastSeenSeq.get(row.walkthroughId) ?? -1;
        store.lastSeenSeq.set(row.walkthroughId, Math.max(existingSeq, row.seqAt));
      }
    }
  } catch (e) {
    wtTrace(
      "lifecycle",
      `hydrateActiveWalkthroughs failed: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
}

/**
 * Stamp `submittedAt` on the given walkthrough issues so the UI's "already
 * posted to GitHub" treatment renders immediately after a Submit/Approve
 * succeeds.
 */
export function markIssuesAsSubmitted(
  prId: string,
  issueIds: readonly string[],
  submittedAt: string,
): void {
  if (issueIds.length === 0) return;
  const idSet = new Set(issueIds);
  updateEntry(prId, (entry) => {
    entry.issues = entry.issues.map((i) => (idSet.has(i.id) ? { ...i, submittedAt } : i));
  });
}

// ── Pre-mount setup ─────────────────────────────────────────────────────────

/**
 * Synchronously mark a PR as active and seed a "loading" entry if one
 * doesn't already exist. Runs on component mount before the hydration
 * fetch resolves, so the UI renders the skeleton immediately instead of
 * briefly flashing the empty state.
 */
export function prepareEntry(prId: string, mode: WalkthroughMode = getSelectedMode(prId)): void {
  store.activePrId = prId;
  const existing = store.entries.get(prId);
  if (
    existing &&
    existing.mode === mode &&
    existing.summary !== null &&
    existing.blocks.length > 0 &&
    existing.doneReceived &&
    !existing.streamError
  ) {
    return;
  }
  if (existing && existing.mode === mode) return;
  setEntry(prId, {
    ...freshEntry(),
    mode,
    isStreaming: false,
    phaseMessage: "",
    streamStartedAt: null,
  });
}

/**
 * Mark the active PR as deselected. With the global SSE bus there is no
 * per-PR subscription to close — generation continues in the background
 * and events still arrive for the entry, which is exactly what we want
 * when navigating between PRs.
 */
export function deactivate(): void {
  store.activePrId = null;
}

// ── Cache hydration ─────────────────────────────────────────────────────────

const pendingHydration = new Map<string, Promise<boolean>>();

/**
 * The walkthrough mode for a PR. Derived purely from identity (author vs.
 * signed-in user) via the PR store — no manual selection. Both an author and
 * a reviewer walkthrough may exist server-side per head SHA; the viewer's
 * role decides which one this client hydrates and generates.
 */
export function getSelectedMode(prId: string): WalkthroughMode {
  return getReviewModeForPr(prId);
}

/**
 * Read current walkthrough state for `prId` and reconcile it into the
 * reactive store. The only client path that returns walkthrough content
 * without potentially triggering generation. Called from
 * `GuidedWalkthrough.onMount` to render instantly on cache hit; live
 * progress for an in-flight job arrives via the global SSE bus.
 */
export async function hydrateFromCache(
  prId: string,
  options?: {
    activate?: boolean;
    mode?: WalkthroughMode;
    replace?: boolean;
    reportId?: string | null;
  },
): Promise<boolean> {
  const mode = options?.mode ?? getSelectedMode(prId);
  const reportId = options?.reportId ?? null;
  const key = `${prId}:${mode}:${reportId ?? "current"}`;
  const inflight = pendingHydration.get(key);
  if (inflight) {
    wtTrace("lifecycle", `hydrateFromCache deduped prId=${prId}`);
    return inflight;
  }

  const promise = doHydrateFromCache(prId, { ...options, mode });
  pendingHydration.set(key, promise);
  try {
    return await promise;
  } finally {
    pendingHydration.delete(key);
  }
}

async function doHydrateFromCache(
  prId: string,
  options?: {
    activate?: boolean;
    mode?: WalkthroughMode;
    replace?: boolean;
    reportId?: string | null;
  },
): Promise<boolean> {
  const mode = options?.mode ?? getSelectedMode(prId);
  const reportId = options?.reportId ?? null;
  wtTrace("lifecycle", `hydrateFromCache enter prId=${prId}`);
  const existing = store.entries.get(prId);
  if (
    !options?.replace &&
    reportId === null &&
    existing &&
    existing.mode === mode &&
    existing.summary !== null &&
    existing.blocks.length > 0 &&
    existing.doneReceived &&
    !existing.streamError
  ) {
    wtTrace("lifecycle", `hydrateFromCache skip prId=${prId} reason=already-complete`);
    if (options?.activate !== false) {
      store.activePrId = prId;
    }
    return true;
  }

  try {
    const endpoint =
      reportId === null
        ? `${API_BASE_URL}/api/reviews/${prId}/walkthrough/current?mode=${mode}`
        : `${API_BASE_URL}/api/reviews/${prId}/walkthrough/report/${reportId}?mode=${mode}`;
    const res = await fetch(endpoint, {
      headers: authHeaders(),
      credentials: "include",
    });
    if (!res.ok) {
      wtTrace("lifecycle", `hydrateFromCache prId=${prId} httpStatus=${res.status} → false`);
      return false;
    }

    type WalkthroughPayload = {
      id: string;
      mode?: WalkthroughMode;
      summary: string;
      riskLevel: RiskLevel;
      sentiment?: string | null;
      lastCompletedPhase?: WalkthroughPipelinePhase;
      semanticSteps?: WalkthroughSemanticStep[];
      blocks: WalkthroughBlock[];
      issues: WalkthroughIssue[];
      ratings: WalkthroughRating[];
      tokenUsage: unknown;
      reviewSessionId: string;
      generatedBy?: {
        githubUserId: number | null;
        githubLogin: string | null;
        displayName: string | null;
        avatarContent: string | null;
      } | null;
      providerConfig?: {
        provider: string;
        model: string;
        thinkingEffort: string | null;
        contextWindow: string | null;
        maxTurns: number;
      } | null;
    };

    const body = (await res.json()) as
      | { status: "not_found" }
      | {
          status: "complete" | "generating" | "error" | "superseded";
          walkthrough: WalkthroughPayload;
          snapshotAt: string;
          seqAt?: number;
          stale?: boolean;
          historical?: boolean;
        };

    if (body.status === "not_found") {
      wtTrace("lifecycle", `hydrateFromCache prId=${prId} status=not_found → false`);
      return false;
    }

    const wt = body.walkthrough;
    const { status } = body;
    const isGenerating = status === "generating";
    const isError = status === "error";
    const isHistorical = body.historical === true && !isGenerating;
    wtTrace(
      "lifecycle",
      `hydrateFromCache prId=${prId} status=${status} blocks=${wt.blocks.length} issues=${wt.issues.length} ratings=${wt.ratings.length} semanticSteps=${wt.semanticSteps?.length ?? 0} hasSentiment=${wt.sentiment !== null && wt.sentiment !== undefined}`,
    );

    const previous = options?.replace ? undefined : store.entries.get(prId);
    // Clone (don't reuse `previous`): `setEntry` writes into a SvelteMap, whose
    // `set` only fires reactivity when the stored *reference* changes
    // (`prev_res !== value`). Mutating `previous` in place and re-setting the
    // same object would land the data in the map but never notify subscribers —
    // the UI stays on the pre-hydration empty state until a remount reads the
    // entry fresh (the "reload shows nothing, but switching PRs and back fixes
    // it" bug). A fresh object guarantees the write is observed.
    const entry: WalkthroughEntry = previous ? { ...previous } : freshEntry();
    entry.mode = wt.mode ?? mode;
    const hasRealSummary = wt.summary !== "";

    // Entry-wins merge: SSE events applied to `entry` during the REST fetch
    // are newer than the snapshot in `wt`, so prefer entry's non-null values
    // for scalars and overlay entry items on top of snapshot items for
    // collections. Without this, the snapshot's stale view would clobber
    // chapters the SSE had already delivered.
    entry.summary = entry.summary ?? (hasRealSummary ? wt.summary : null);
    entry.riskLevel = entry.riskLevel ?? (hasRealSummary ? wt.riskLevel : null);
    entry.sentiment = entry.sentiment ?? wt.sentiment ?? null;

    const snapshotPhase = wt.lastCompletedPhase ?? (isGenerating ? "none" : "D");
    const entryPhase = entry.lastCompletedPhase ?? "none";
    entry.lastCompletedPhase =
      PHASE_RANK[entryPhase] >= PHASE_RANK[snapshotPhase] ? entryPhase : snapshotPhase;

    const ssMap = new Map<number, WalkthroughSemanticStep>();
    for (const s of wt.semanticSteps ?? []) ssMap.set(s.semanticStepIndex, s);
    for (const s of entry.semanticSteps) ssMap.set(s.semanticStepIndex, s);
    entry.semanticSteps = Array.from(ssMap.values()).sort(
      (a, b) => a.semanticStepIndex - b.semanticStepIndex,
    );

    const blockMap = new Map<string, WalkthroughBlock>();
    for (const b of wt.blocks) blockMap.set(b.id, b);
    for (const b of entry.blocks) blockMap.set(b.id, b);
    entry.blocks = Array.from(blockMap.values()).sort((a, b) => a.order - b.order);

    const issueMap = new Map<string, WalkthroughIssue>();
    for (const i of wt.issues) issueMap.set(i.id, i);
    for (const i of entry.issues) issueMap.set(i.id, i);
    entry.issues = Array.from(issueMap.values());

    const ratingMap = new Map<string, WalkthroughRating>();
    for (const r of wt.ratings) ratingMap.set(r.axis, r);
    for (const r of entry.ratings) ratingMap.set(r.axis, r);
    entry.ratings = Array.from(ratingMap.values());

    entry.walkthroughId = wt.id;
    entry.doneReceived = !isGenerating && !isError;
    entry.isStreaming = isGenerating;
    entry.tokenUsage = coerceTokenUsage(wt.tokenUsage);
    entry.streamError = isError
      ? isHistorical
        ? null
        : "Walkthrough generation failed. Resume or regenerate to retry."
      : null;
    entry.superseded = body.stale === true;
    entry.historical = isHistorical;
    entry.phase = isGenerating ? "writing" : "finishing";
    entry.phaseMessage = isGenerating ? "Resuming walkthrough…" : "Complete";
    entry.liveGeneration = isGenerating;
    entry.generatedBy = wt.generatedBy ?? entry.generatedBy ?? null;
    entry.providerConfig = wt.providerConfig ?? entry.providerConfig ?? null;
    if (previous?.source === "remote") entry.source = "remote";
    if (isGenerating) entry.streamStartedAt = Date.now();
    setEntry(prId, entry);
    store.selectedReportIds.set(prId, isHistorical ? wt.id : null);

    // Math.max so SSE can't regress the cursor below what it already advanced
    // past during the fetch window.
    if (typeof body.seqAt === "number") {
      const existingSeq = store.lastSeenSeq.get(wt.id) ?? -1;
      store.lastSeenSeq.set(wt.id, Math.max(existingSeq, body.seqAt));
    }

    if (options?.activate !== false) {
      store.activePrId = prId;
    }

    return true;
  } catch (e) {
    wtTrace(
      "lifecycle",
      `hydrateFromCache prId=${prId} error=${e instanceof Error ? e.message : String(e)}`,
    );
    return false;
  }
}

// ── Clone polling ───────────────────────────────────────────────────────────

const clonePollers = new Map<string, { cancelled: boolean }>();
const CLONE_POLL_INTERVAL_MS = 2000;
const CLONE_POLL_MAX_MS = 10 * 60 * 1000;

export function stopClonePoll(prId: string): void {
  const p = clonePollers.get(prId);
  if (p) p.cancelled = true;
  clonePollers.delete(prId);
}

export async function pollCloneUntilResolved(
  prId: string,
  repoId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
): Promise<void> {
  if (clonePollers.has(prId)) return;
  const token = { cancelled: false };
  clonePollers.set(prId, token);
  const startedAt = Date.now();
  try {
    while (!token.cancelled) {
      const entry = store.entries.get(prId);
      if (!entry?.cloneInProgress || entry.cloneRepoId !== repoId) return;

      let status: CloneStatus = "cloning";
      let error: string | null = null;
      try {
        const { data } = await api.api.repos({ id: repoId })["clone-status"].get();
        if (data && "status" in data) {
          status = data.status;
          error = data.error ?? null;
        }
      } catch {
        // Transient network blip — keep polling.
      }

      if (token.cancelled) return;

      updateRepoCloneStatus(repoId, status, error ?? undefined);

      if (status === "ready") {
        // Clone finished — kick off generation; server will broadcast
        // `lifecycle:started` and content events via the global SSE bus.
        void startWalkthrough(prId, mode);
        return;
      }
      if (status === "error" || status === "pending") {
        updateEntry(prId, (e) => {
          e.cloneInProgress = false;
          e.cloneRepoId = null;
          e.isStreaming = false;
          e.streamError =
            status === "error"
              ? `Repository clone failed${error ? `: ${error}` : ""}. Retry to try again.`
              : "Repository clone was reset. Retry to try again.";
        });
        return;
      }

      if (Date.now() - startedAt > CLONE_POLL_MAX_MS) {
        updateEntry(prId, (e) => {
          e.cloneInProgress = false;
          e.cloneRepoId = null;
          e.isStreaming = false;
          e.streamError = "Repository clone is taking too long. Retry to try again.";
        });
        return;
      }

      await new Promise((r) => setTimeout(r, CLONE_POLL_INTERVAL_MS));
    }
  } finally {
    if (clonePollers.get(prId) === token) clonePollers.delete(prId);
  }
}

// ── User-driven actions (REST → server broadcasts via SSE bus) ──────────────

/**
 * Thin POST that asks the server to start a walkthrough. Server-side is
 * idempotent — if a job is already running for this PR's head SHA the
 * existing walkthroughId is returned. Used by `regenerate()` (which has
 * already cleared its own entry) and by the after-clone callers
 * (GuidedWalkthrough effect, `pollCloneUntilResolved`), both of which
 * keep their own UI state and just need the server-side job kicked off.
 * UI-facing button clicks should use {@link generateWalkthrough} instead,
 * which adds the pending-action + optimistic-seed feedback.
 */
export async function startWalkthrough(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
  generationMode: "full" | "incremental" = "full",
): Promise<Response | null> {
  try {
    return await fetch(`${API_BASE_URL}/api/reviews/${prId}/walkthrough/start`, {
      method: "POST",
      headers: { ...authHeaders(), "Content-Type": "application/json" },
      body: JSON.stringify({ mode, generationMode }),
    });
  } catch (e) {
    wtTrace(
      "lifecycle",
      `startWalkthrough prId=${prId} error=${e instanceof Error ? e.message : String(e)}`,
    );
    return null;
  }
}

/**
 * User-action wrapper for the "Generate walkthrough" button. Sets a pending
 * action so the button stays disabled across the round-trip and
 * optimistically seeds a streaming entry so the action bar flips to "Stop
 * generation" immediately — without this the server can spend seconds on
 * resolveWithDiff + agent daemon boot before emitting `lifecycle:started`,
 * and the click looks like a no-op. The button is template-gated on the
 * UI state being `absent` or `idle`, so the seed is always safe here.
 */
export async function generateWalkthrough(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
): Promise<void> {
  if (pendingActions.map.has(prId)) return;
  setPending(prId, "start");

  const seed = freshEntry();
  seed.mode = mode;
  seed.phaseMessage = "Starting walkthrough…";
  seed.historical = false;
  store.selectedReportIds.set(prId, null);
  setEntry(prId, seed);
  store.activePrId = prId;

  try {
    const res = await startWalkthrough(prId, mode);
    if (!res) {
      updateEntry(prId, (e) => {
        e.isStreaming = false;
        e.streamError = "Failed to start walkthrough";
      });
    } else if (!res.ok) {
      updateEntry(prId, (e) => {
        e.isStreaming = false;
        e.streamError = `Failed to start walkthrough (HTTP ${res.status}).`;
      });
    }
  } finally {
    clearPending(prId);
  }
}

/**
 * Stop the in-flight walkthrough. Flips local UI state immediately for
 * snappy feedback, then fires-and-forgets a `POST /walkthrough/abort` so
 * the server actually interrupts the fiber. Without the server call the
 * Stop button only relabeled the UI while the agent kept burning tokens
 * in the background. The server's interrupt path emits `lifecycle:error`
 * with code `'Cancelled'`, which the reducer turns into the post-stop
 * state (Resume/Regenerate buttons).
 */
export function abort(prId: string): void {
  const mode = getSelectedMode(prId);
  updateEntry(prId, (e) => {
    e.isStreaming = false;
    e.streamError = null;
  });
  // Stop is the user's explicit "walk away" signal — drop any in-flight
  // pending action so the Generate / Regenerate / Resume button re-enables
  // immediately. Without this, a hung `start` / `regenerate` fetch keeps
  // pendingAction set until its `finally` runs, which may be never.
  clearPending(prId);
  stopClonePoll(prId);
  // Fire-and-forget. Failures are best-effort: if the request fails the
  // server-side fiber keeps running, but the local UI has already moved
  // on, and the next pull/regenerate will catch the leak.
  fetch(`${API_BASE_URL}/api/reviews/${prId}/walkthrough/abort`, {
    method: "POST",
    headers: { ...authHeaders(), "Content-Type": "application/json" },
    body: JSON.stringify({ mode }),
  }).catch(() => {
    /* best-effort */
  });
}

export async function regenerate(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
  generationMode: "full" | "incremental" = "incremental",
): Promise<void> {
  if (pendingActions.map.has(prId)) return;
  setPending(prId, "regenerate");
  try {
    clearAnimationTrackers(prId);
    deleteEntry(prId);
    store.selectedReportIds.set(prId, null);
    store.activePrId = prId;

    const entry = freshEntry();
    entry.mode = mode;
    entry.historical = false;
    entry.phaseMessage =
      generationMode === "incremental" ? "Reviewing new commits..." : "Regenerating...";
    setEntry(prId, entry);

    try {
      await fetch(`${API_BASE_URL}/api/reviews/${prId}/walkthrough/regenerate`, {
        method: "POST",
        headers: { ...authHeaders(), "Content-Type": "application/json" },
        body: JSON.stringify({ mode, generationMode }),
      });
    } catch {
      // Non-fatal — the start call below will still create a fresh job.
    }

    // Keep the seeded freshEntry in place across the start POST: the
    // `lifecycle:started` reducer patches `walkthroughId` on the existing
    // entry, so dropping it here would only cause `_active` to flip to
    // undefined and flash the "Generate walkthrough" pill between the
    // regenerate and start round-trips.
    const res = await startWalkthrough(prId, mode, generationMode);
    if (!res) {
      updateEntry(prId, (e) => {
        e.isStreaming = false;
        e.streamError = "Failed to start walkthrough";
      });
      return;
    }
    if (!res.ok) {
      updateEntry(prId, (e) => {
        e.isStreaming = false;
        e.streamError = `Failed to start walkthrough (HTTP ${res.status}).`;
      });
      return;
    }

    const started = (await res.json().catch(() => null)) as { walkthroughId?: string } | null;
    if (started?.walkthroughId) {
      await hydrateFromCache(prId, {
        mode,
        reportId: started.walkthroughId,
        replace: true,
      });
    }
  } finally {
    clearPending(prId);
  }
}

export function regenerateFromScratch(prId: string): Promise<void> {
  return regenerate(prId, getSelectedMode(prId), "full");
}

export async function resume(
  prId: string,
  mode: WalkthroughMode = getSelectedMode(prId),
): Promise<void> {
  if (pendingActions.map.has(prId)) return;
  setPending(prId, "resume");
  try {
    updateEntry(prId, (e) => {
      e.streamError = null;
    });
    try {
      const res = await fetch(`${API_BASE_URL}/api/reviews/${prId}/walkthrough/resume`, {
        method: "POST",
        headers: { ...authHeaders(), "Content-Type": "application/json" },
        body: JSON.stringify({ mode }),
      });
      if (!res.ok) {
        updateEntry(prId, (e) => {
          e.streamError =
            res.status === 404
              ? "No resumable walkthrough was found. Review new commits or regenerate instead."
              : `Failed to resume walkthrough (HTTP ${res.status}).`;
        });
      }
    } catch (err) {
      updateEntry(prId, (e) => {
        e.streamError = `Failed to resume walkthrough: ${
          err instanceof Error ? err.message : String(err)
        }`;
      });
    }
  } finally {
    clearPending(prId);
  }
}

/**
 * Called when a new commit pulled in for the PR invalidates the
 * existing walkthrough. Marks the rows superseded server-side without
 * starting a fresh job — the user opts in to regenerate explicitly via
 * the Generate button.
 */
export async function invalidateForPull(prId: string): Promise<void> {
  clearAnimationTrackers(prId);
  updateEntry(prId, (entry) => {
    entry.superseded = true;
    entry.isStreaming = false;
    entry.liveGeneration = false;
    entry.streamError = null;
  });
  try {
    await fetch(`${API_BASE_URL}/api/reviews/${prId}/walkthrough/regenerate`, {
      method: "POST",
      headers: authHeaders(),
    });
  } catch {
    // Non-fatal.
  }
}

// ── Animated block tracking ─────────────────────────────────────────────────
//
// Non-reactive — tracks which block/issue/container IDs have already animated,
// keyed by PR ID. Lives outside `entries` so it survives component remounts.
// Cleared on regenerate/invalidateForPull via clearAnimationTrackers().

const animatedBlocks = new Map<string, Set<string>>();
const animatedIssues = new Map<string, Set<string>>();
const animatedContainers = new Map<string, Set<string>>();

export function clearAnimationTrackers(prId: string): void {
  animatedBlocks.delete(prId);
  animatedIssues.delete(prId);
  animatedContainers.delete(prId);
}

export function hasBlockAnimated(prId: string, blockId: string): boolean {
  return animatedBlocks.get(prId)?.has(blockId) ?? false;
}
export function markBlockAnimated(prId: string, blockId: string): void {
  let set = animatedBlocks.get(prId);
  if (!set) {
    set = new Set();
    animatedBlocks.set(prId, set);
  }
  set.add(blockId);
}

export function hasIssueAnimated(prId: string, issueId: string): boolean {
  return animatedIssues.get(prId)?.has(issueId) ?? false;
}
export function markIssueAnimated(prId: string, issueId: string): void {
  let set = animatedIssues.get(prId);
  if (!set) {
    set = new Set();
    animatedIssues.set(prId, set);
  }
  set.add(issueId);
}

export function hasContainerAnimated(prId: string, key: string): boolean {
  return animatedContainers.get(prId)?.has(key) ?? false;
}
export function markContainerAnimated(prId: string, key: string): void {
  let set = animatedContainers.get(prId);
  if (!set) {
    set = new Set();
    animatedContainers.set(prId, set);
  }
  set.add(key);
}
