<script lang="ts">
import { ArrowLeft, CircleAlert, Loader2, RefreshCw } from "@lucide/svelte";
import type { ProjectRecap } from "@revv/shared";
import { renderMarkdown } from "$lib/utils/markdown";
import RecapStats from "./RecapStats.svelte";

interface Props {
  recap: ProjectRecap | null;
  loading: boolean;
  onBack: () => void;
  onRegenerate: () => void;
  regenerating?: boolean;
}

let { recap, loading, onBack, onRegenerate, regenerating = false }: Props = $props();

let html = $derived(recap?.overview ? renderMarkdown(recap.overview) : "");

function formatPeriod(r: ProjectRecap): string {
  const start = new Date(r.periodStart);
  const end = new Date(r.periodEnd);
  if (r.period === "daily") {
    return `Daily · ${start.toUTCString().slice(0, 16)} UTC`;
  }
  const startStr = start.toUTCString().slice(8, 16);
  const endStr = end.toUTCString().slice(8, 16);
  return `Weekly · ${startStr} → ${endStr} UTC`;
}
</script>

<div class="recap-detail">
	<header class="recap-detail-header">
		<button type="button" class="back-btn" onclick={onBack}>
			<ArrowLeft size={14} />
			<span>Recaps</span>
		</button>
		{#if recap}
			<div class="period">{formatPeriod(recap)}</div>
			<button
				type="button"
				class="regen-btn"
				onclick={onRegenerate}
				disabled={regenerating || recap.status === "generating"}
				title="Generate a fresh recap for this period (the current one becomes superseded)"
			>
				{#if regenerating}
					<Loader2 size={12} class="animate-spin" />
				{:else}
					<RefreshCw size={12} />
				{/if}
				<span>Regenerate</span>
			</button>
		{/if}
	</header>

	{#if loading && !recap}
		<div class="recap-loading">
			<Loader2 size={24} class="animate-spin" aria-hidden="true" />
			<p>Loading recap…</p>
		</div>
	{:else if !recap}
		<div class="recap-empty">
			<CircleAlert size={24} aria-hidden="true" />
			<p>Recap not found.</p>
		</div>
	{:else}
		<div class="recap-stats-row">
			<RecapStats stats={recap.summaryStats} />
		</div>

		{#if recap.status === "generating"}
			<div class="recap-pending">
				<Loader2 size={18} class="animate-spin" aria-hidden="true" />
				<div>
					<p>Generating…</p>
					<p class="hint">
						This page will update automatically when the recap finishes. You can
						leave and come back.
					</p>
				</div>
			</div>
		{:else if recap.status === "error"}
			<div class="recap-pending recap-pending--error">
				<CircleAlert size={18} aria-hidden="true" />
				<div>
					<p>Generation failed.</p>
					<p class="hint">
						Click "Regenerate" to try again. If this happens repeatedly, check
						that the Claude agent is selected in Settings — recap generation
						currently requires Claude.
					</p>
				</div>
			</div>
		{:else if recap.status === "superseded"}
			<div class="recap-pending">
				<p>This recap has been replaced by a newer one for the same period.</p>
			</div>
		{:else if !recap.overview}
			<div class="recap-pending">
				<p>No overview content was written by the agent.</p>
			</div>
		{:else}
			<article class="recap-prose">
				{@html html}
			</article>
		{/if}

		{#if recap.completedAt}
			<footer class="recap-detail-footer">
				<span>
					Generated by {recap.modelUsed ?? "claude"} ·
					{recap.sourcePrIds.length} source PR{recap.sourcePrIds.length === 1 ? '' : 's'} ·
					completed {new Date(recap.completedAt).toUTCString()}
				</span>
			</footer>
		{/if}
	{/if}
</div>

<style>
	.recap-detail {
		display: flex;
		flex-direction: column;
		gap: 1rem;
		padding: 1rem 1.25rem 2rem;
		max-width: 56rem;
		margin: 0 auto;
		width: 100%;
	}

	.recap-detail-header {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		padding-bottom: 0.5rem;
		border-bottom: 1px solid var(--color-border-subtle);
	}

	.back-btn {
		display: inline-flex;
		align-items: center;
		gap: 0.25rem;
		padding: 0.25rem 0.5rem;
		font-size: 0.8125rem;
		color: var(--color-text-secondary);
		background: transparent;
		border: none;
		border-radius: 0.25rem;
		cursor: pointer;
		transition: background var(--duration-snap) var(--ease-out-expo);
	}

	.back-btn:hover {
		background: var(--color-bg-secondary);
		color: var(--color-text-primary);
	}

	.period {
		flex: 1;
		font-size: 0.9375rem;
		color: var(--color-text-primary);
	}

	.regen-btn {
		display: inline-flex;
		align-items: center;
		gap: 0.375rem;
		padding: 0.25rem 0.625rem;
		font-size: 0.75rem;
		color: var(--color-text-primary);
		background: var(--color-bg-secondary);
		border: 1px solid var(--color-border-subtle);
		border-radius: 0.25rem;
		cursor: pointer;
		transition: background var(--duration-quick) var(--ease-out-expo);
	}

	.regen-btn:hover:not(:disabled) {
		background: var(--color-bg-hover, var(--color-bg-secondary));
	}

	.regen-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.recap-stats-row {
		padding: 0.25rem 0;
	}

	.recap-pending,
	.recap-loading,
	.recap-empty {
		display: flex;
		gap: 0.625rem;
		align-items: flex-start;
		padding: 1rem 1.25rem;
		background: var(--color-bg-secondary);
		border-radius: 0.5rem;
		color: var(--color-text-secondary);
	}

	.recap-pending p {
		margin: 0;
	}

	.recap-pending .hint,
	.recap-empty p + p {
		margin-top: 0.25rem;
		font-size: 0.8125rem;
		color: var(--color-text-muted);
	}

	.recap-pending--error {
		color: var(--color-text-primary);
	}

	.recap-prose {
		font-size: 0.9375rem;
		line-height: 1.6;
		color: var(--color-text-primary);
	}

	.recap-prose :global(h1),
	.recap-prose :global(h2),
	.recap-prose :global(h3) {
		margin: 1.5em 0 0.5em;
		font-weight: 600;
	}

	.recap-prose :global(p) {
		margin: 0.75em 0;
	}

	.recap-prose :global(ul),
	.recap-prose :global(ol) {
		margin: 0.5em 0;
		padding-left: 1.5em;
	}

	.recap-prose :global(li) {
		margin: 0.25em 0;
	}

	.recap-prose :global(code) {
		font-family: var(--font-mono, monospace);
		font-size: 0.875em;
		padding: 0.125em 0.375em;
		background: var(--color-bg-secondary);
		border-radius: 0.25em;
	}

	.recap-detail-footer {
		padding-top: 0.5rem;
		border-top: 1px solid var(--color-border-subtle);
		font-size: 0.75rem;
		color: var(--color-text-muted);
	}
</style>
